### ISSUE TITLE
Line length = 81 after converting

### ISSUE THREAD

**Issue by pymen** [hhatto/autopep8#138]
command:
autopep8 --in-place -a --experimental ./temp/pep8try

as you can see line 
'                'code': u'ru', 'name': u'Russian', 'region_lead': None, 'id': 1,'
has length 81 after converting

Here is source example:

    class TestLSView(setUpReviewerMixin, TestCase):

        def test_ls(self):
            self.maxDiff = None
            request = Request().get_request()
            e = {
                'langs':
                [{'language_owner':
                    [{'nickname': u'Language Owner', 'id': 9,
                      'email': u'language@owner.com'}],
                    'code': u'ru', 'name': u'Russian', 'region_lead': None, 'id': 1,
                    'OXL': [],
                    'subregion': '',
                    'LS':
                    [{'nickname': u'r1', 'id': 1, 'email': u'r1@email.com'},
                        {'nickname': u'r2', 'id': 2, 'email': u'r2@email.com'},
                        {'nickname': u'r8', 'id': 8, 'email': u'r8@email.com'}],
                    'OLXL': [],
                    'region': u'ASIA'}]}

**Comment by myint** [comment]
Fixed in 4a02947c1983f1d129eb748823ce829c7a946357.
