### ISSUE TITLE
Autopep8 is adding new lines between a class declaration and the docstring after it.

### ISSUE THREAD

**Issue by fabioz** [hhatto/autopep8#178]
To reproduce consider:

```
class MenuCreator(object):
    '''Helper class to create menus.'''
```

is becoming 

```
class MenuCreator(object):

    '''Helper class to create menus.'''
```

i.e.: the new line after the class and before the docstring is being added by autopep8 (when I think it shouldn't).

**Comment by SmileyChris** [comment]
What's E309 anyway? It's not referenced in the pep8 docs, and (looking at code) seems just plain incorrect to include docstrings as one of the definitive conditions of this.
