### ISSUE TITLE
A blank line between classes is not added, if they're defined inside an if statement

### ISSUE THREAD

**Issue by snapy666** [hhatto/autopep8#186]
As stated in [PEP8](https://www.python.org/dev/peps/pep-0008/#blank-lines):
> Separate top-level function and class definitions with two blank lines.

```python
if __name__ == '__main__':
    class Pos:

        def __init__(self, x, y):
            self.x = x
            self.y = y

    class Lifetime:
        
        def __init__(self, lifetime):
            if lifetime < 0:
                raise ValueError('lifetime must be above 0')
            self.lifetime = lifetime

    class Name:

        def __init__(self, name):
            self.name = '"' + name + '"'
```

---
```
$ autopep8 --version
autopep8 1.0.3

$ pep8 --version
1.5.7

$ python --version
Python 2.7.6

$ uname -a
Linux s-PC 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
---

*Side question:* Is there a flag to stop autopep8 from adding a blank line after, for example, the `class Lifetime:` (before `__init__`)?

**Comment by myint** [comment]
In answer to your side question, `--ignore=E309`.

**Comment by myint** [comment]
`pep8` does not report a blank line being needed. So this issue probably should be reported [there](https://github.com/jcrocholl/pep8/issues).
