### ISSUE TITLE
autopep8 throws "unknown encoding" when run as a filter from MacVim

### ISSUE THREAD

**Issue by mario-grgic** [hhatto/autopep8#189]
I'm trying to use autopep8 from MacVim by invoking it like this:

:%!/usr/local/bin/autopep8 -

which basically sends entire contents of buffer in MacVim and pipes it to autopep8. This however leads to the following stack trace:

Traceback (most recent call last):
  File "/usr/local/bin/autopep8", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/autopep8.py", line 3728, in main
    wrap_output(sys.stdout, encoding=encoding).write(
  File "/Library/Python/2.7/site-packages/autopep8.py", line 3698, in wrap_output
    return codecs.getwriter(encoding)(output.buffer
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 994, in getwriter
    return lookup(encoding).streamwriter
LookupError: unknown encoding: 

The encoding is computed as 

            encoding = sys.stdin.encoding or locale.getpreferredencoding()

but when invoked from MacVim this returns None. I wonder if there is a better way to figure out default locale encoding (which on Mac OS X happens to be UTF-8)?

**Comment by mario-grgic** [comment]
When I run this script from MacVim 

    #!/usr/bin/python

    import sys
    import locale

    print sys.stdin.encoding
    print locale.getpreferredencoding()
    print sys.getdefaultencoding()
    print sys.getfilesystemencoding()

I get the following output:

None

ascii
utf-8

**Comment by myint** [comment]
Thanks for the detailed report. Could you try the latest (026961903b17025865a94b9662ba4a29fb65c8d1) on the master branch?

```
$ pip install --upgrade git+https://github.com/hhatto/autopep8
```

**Comment by mario-grgic** [comment]
This fixes it. Thank you.
