### ISSUE TITLE
Any plan for "import *" ?

### ISSUE THREAD

**Issue by douglarek** [hhatto/autopep8#190]
@hhatto I like `autopep8` very much, and I always use it now, BTW: any plan for this ?

example:

```
from os import *
```

to be:

```
from os import path, chmod
```

**Comment by hhatto** [comment]
@myint 
Do you support in autoflake?
https://github.com/myint/autoflake

**Comment by myint** [comment]
@hhatto, No, autoflake does not support that. I think that requires some kind of autocompletion-like tool.

**Comment by hhatto** [comment]
@douglarek 
Sorry for late replay.

There are no plans to support for now.
If if pep8 is to support, I will support any autopep8.
