### ISSUE TITLE
Formatting code fragments: assume the first line is indented correctly

### ISSUE THREAD

**Issue by kiryph** [hhatto/autopep8#198]
I have set in vim `formatprg` to autopep8 for python files.
Often I apply the formatprogram via the command`gq` only to a code fragment which has a common indentation level which I want to keep.

The code formatter [uncrustify](http://uncrustify.sourceforge.net/) offers a command line flag `--frag` which assumes that the first line of input is correctly indented.

Is it possible to add to autopep8 a similar option, so I can adjust setting `formatprg`?

**Comment by myint** [comment]
See [this](https://github.com/hhatto/autopep8/blob/master/test/vim_autopep8.py) for an example of how to enable this.

**Comment by kiryph** [comment]
Thank you for pointing this out. However, the proposed mapping `<C-I>` is unfortunate (overrides important default mapping) and the usage of this mapping is from my point of view not vimish (cannot be combined with motions and textobjects). I think the `gq` functionality is precisely meant for this.
Usage of `visual mode` should only be optional not mandatory to apply autopep8 to a code fragment.

I have found another suggestion on [stackoverflow](http://stackoverflow.com/questions/24449056/how-to-set-correct-indendation-when-using-formatprg-autopep8) to disable indenting. I can live with this because vim has beside gq (`formatprg`) the `=` (`equalprg`) mapping for reindentation.

Just for reference a list of relevant vim plugins, which however also do not setup `gq` properly:
https://github.com/tell-k/vim-autopep8
https://github.com/klen/python-mode

To fix indentation the python source code itself contains a script `reindent.py`:
http://svn.python.org/view/python/trunk/Tools/scripts/reindent.py?revision=66903&view=markup

**Comment by kiryph** [comment]
Another 2 cents: having the same command `gq` working for different languages is much more user friendly. Consistency should always be preferred.

**Comment by myint** [comment]
Sure. The `vim_autopep8` that I referred to above is for example only. I think it would make sense for you to modify one of the autopep8 Vim plugins you mention to make use of `--range` as shown in the [example](https://github.com/hhatto/autopep8/blob/master/test/vim_autopep8.py#L41). (I don't personally use autopep8 inside Vim. I basically use autopep8 in batch mode to clean up old code bases before starting to work on them.)
