### ISSUE TITLE
parse_args API when using autopep8 as a module

### ISSUE THREAD

**Issue by hayd** [hhatto/autopep8#200]
It often System Error when passing something that looks like it ought to work. The README advertises using autopep8 as a module so passing args seems a reasonable thing to do, yet it very fiddly atm.
```
In [23]: parse_args('')
usage: autopep8 [-h] [--version] [-v] [-d] [-i] [--global-config filename]
                [--ignore-local-config] [-r] [-j n] [-p n] [-a]
                [--experimental] [--exclude globs] [--list-fixes]
                [--ignore errors] [--select errors] [--max-line-length n]
                [--range line line] [--indent-size n]
                [files [files ...]]
autopep8: error: incorrect number of arguments
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

To exit: use 'exit', 'quit', or Ctrl-D.

In [24]: parse_args([''])
Out[24]: Namespace(aggressive=0, diff=False, exclude=[], experimental=False, files=[u''], global_config=u'/Users/andy/.config/pep8', ignore=set([u'E24']), ignore_local_config=False, in_place=False, indent_size=4, jobs=1, line_range=None, list_fixes=False, max_line_length=79, pep8_passes=-1, recursive=False, select=u'', verbose=0)

In [25]: parse_args(['--range 1 10'])
Out[25]: Namespace(aggressive=0, diff=False, exclude=[], experimental=False, files=[u'--range 1 10'], global_config=u'/Users/andy/.config/pep8', ignore=set([u'E24']), ignore_local_config=False, in_place=False, indent_size=4, jobs=1, line_range=None, list_fixes=False, max_line_length=79, pep8_passes=-1, recursive=False, select=u'', verbose=0)
```
Perhaps the API could be improved by allowing a dict to be passed.

    fix_code(code, options={"line_range": [1, 10]})
    # equivalent to
    fix_code(code, options=parse_args({"line_range": [1, 10]}))

where

    parse_args(arguments, apply_config=False):
        if isistance(arguments, dict):
            options = parse_args([''], apply_config=apply_config)
            for k, v in arguments.values():
                setattr(options, k, v)
            return options
        ....

**Comment by myint** [comment]
I think it makes sense to allow `fix_code()` to optionally take in a dictionary. (I never really liked the way it is now, but kept it for compatibility.) Another option is to create an module-level object with the default options that the user could override. That would avoid using strings, which is kind of nice.

**Comment by hayd** [comment]
fantastic! thanks
