### ISSUE TITLE
Only fix E128 if it does not cause E501

### ISSUE THREAD

**Issue by blueyed** [hhatto/autopep8#203]
`autopep8 --select E128` fixes this one:

             if widget_js_attributes is not None:
                 raise PendingDeprecationWarning('widget_js_attributes are '
    -                    'deprecated in favor of widget_attrs')
    +                                            'deprecated in favor of widget_attrs')

But then it causes E501 (line too long).

It would be useful if the E128 wasn't fixed in this case.

The real / best fix is to change it to the following instead, which would
require to join the strings:

             if widget_js_attributes is not None:
                 raise PendingDeprecationWarning(
                     'widget_js_attributes are deprecated in favor of widget_attrs')

Optionally maybe also:

                 raise PendingDeprecationWarning(
                     'widget_js_attributes are '
                     'deprecated in favor of widget_attrs')

**Comment by myint** [comment]
I'm closing this since `-aa` outputs the last option you mentioned.

```
$ ~/projects/autopep8/autopep8.py -d foo.py -aa
```
```diff
--- original/foo.py
+++ fixed/foo.py
@@ -1,5 +1,6 @@
 if True:
     if True:
         if widget_js_attributes is not None:
-            raise PendingDeprecationWarning('widget_js_attributes are '
-                    'deprecated in favor of widget_attrs')
+            raise PendingDeprecationWarning(
+                'widget_js_attributes are '
+                'deprecated in favor of widget_attrs')
```
