### ISSUE TITLE
E501 not fixed in __all__ list / example

### ISSUE THREAD

**Issue by blueyed** [hhatto/autopep8#204]
With the following example, E501 is not being fixed:

    % cat foo.py 
    __all__ = ['FieldBase', 'ChoiceField', 'MultipleChoiceField',
               'ModelChoiceField', 'ModelMultipleChoiceField', 'GenericModelChoiceField',
               'GenericModelMultipleChoiceField']

    % autopep8 -v foo.py -d
    [file:foo.py]
    --->  Applying global fix for W602
    --->  Applying global fix for E265
    --->  1 issue(s) to fix {'E501': {2}}

It appears to work with another list:

    [file:foo.py]
    --->  2 issue(s) to fix {'E501': {1, 3}}
    --->  1 issue(s) to fix {'E501': {4}}
    --- original/foo.py
    +++ fixed/foo.py
    @@ -1,4 +1,5 @@
    -foo = [foo, bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz]
    +foo = [foo, bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz, foo,
    +    bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz]
     __all__ = ['FieldBase', 'ChoiceField', 'MultipleChoiceField',
                'ModelChoiceField', 'ModelMultipleChoiceField', 'GenericModelChoiceField',
                'GenericModelMultipleChoiceField']

In the second case the second line should be aligned with the first element in the list however:

    +foo = [foo, bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz, foo,
    +       bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz, foo, bar, baz]

autopep8 1.2a0 (git master); pep8 1.5.7 (wasn't upgraded); Python 3.4.3

**Comment by myint** [comment]
```
$ ~/projects/autopep8/autopep8.py -d foo.py -aa
```
```diff
--- original/foo.py
+++ fixed/foo.py
@@ -1,3 +1,8 @@
-__all__ = ['FieldBase', 'ChoiceField', 'MultipleChoiceField',
-           'ModelChoiceField', 'ModelMultipleChoiceField', 'GenericModelChoiceField',
-           'GenericModelMultipleChoiceField']
+__all__ = [
+    'FieldBase',
+    'ChoiceField',
+    'MultipleChoiceField',
+    'ModelChoiceField',
+    'ModelMultipleChoiceField',
+    'GenericModelChoiceField',
+    'GenericModelMultipleChoiceField']
```

```
$ ~/projects/autopep8/autopep8.py -d foo.py --experimental
```
```diff
--- original/foo.py
+++ fixed/foo.py
@@ -1,3 +1,3 @@
 __all__ = ['FieldBase', 'ChoiceField', 'MultipleChoiceField',
-           'ModelChoiceField', 'ModelMultipleChoiceField', 'GenericModelChoiceField',
-           'GenericModelMultipleChoiceField']
+           'ModelChoiceField', 'ModelMultipleChoiceField',
+           'GenericModelChoiceField', 'GenericModelMultipleChoiceField']
```

**Comment by blueyed** [comment]
I see, so the point is to use `-aa` for this then.

However, it should not put them all on a single line, but use up to `max-line-length` for it, shouldn't it?

**Comment by myint** [comment]
The algorithm used in `-aa` does not reflow the lines and simply tries to break the lines up at certain tokens. The `--experimental` mode on the other hand does things a bit more intelligently.
