### ISSUE TITLE
Autoformat failing to correct E501 line too long without --aggressive

### ISSUE THREAD

**Issue by NotTheEconomist** [hhatto/autopep8#205]
Using the Anaconda plugin in SublimeText that implements autopep8, I have the following line:

```python
['Ava firstscher', 'Bob White', 'Chris Rich', 'Danielle Porter', 'Gordon Pike', 'Hannah Beauregard', 'Matt Hoyle', 'Ross Harrison', 'Sasha Ricci', 'Xavier Adams']
```

Obviously this line is too long, but running autopep8 on it reformats to:

```python
['Ava firstscher', 'Bob White', 'Chris Rich', 'Danielle Porter', 'Gordon Pike',
    'Hannah Beauregard', 'Matt Hoyle', 'Ross Harrison', 'Sasha Ricci', 'Xavier Adams']
```

...the second line of which is *also* too long, at 87 characters.

If I run with `--aggressive`, it acts the same, though `--aggressive --aggressive` will reformat to

```python
['Ava firstscher',
    'Bob White',
    'Chris Rich',
    'Danielle Porter',
    'Gordon Pike',
    'Hannah Beauregard',
    'Matt Hoyle',
    'Ross Harrison',
    'Sasha Ricci',
     'Xavier Adams']  # note the weird whitespace here
```

I'm not really sure why it's balking at splitting this list into smaller bits. Any idea?

**Comment by myint** [comment]
The way the default line splitter works is that it splits the line at one location only. In effect, the aggressive mode splits at multiple locations. There is also the `--experimental` mode, which tends to wrap things more intelligently:

```
['Ava firstscher', 'Bob White', 'Chris Rich', 'Danielle Porter', 'Gordon Pike',
 'Hannah Beauregard', 'Matt Hoyle', 'Ross Harrison', 'Sasha Ricci',
 'Xavier Adams']
```
