### ISSUE TITLE
Not receiving results as specified by README

### ISSUE THREAD

**Issue by DavidSnider** [hhatto/autopep8#206]
Hello, 

For some reason when running the given test code with 

    $ autopep8 --in-place --aggressive --aggressive test.py

instead of getting the given resultant code I get this:

    import math
    import sys

    def example1():
        # This is a long comment. This should be wrapped to fit within 72
        # characters.
        some_tuple = (1, 2, 3, 'a')
        some_variable = {
            'long': 'Long code lines should be wrapped within 79 characters.',
            'other': [
                math.pi,
                100,
                200,
                300,
                9876543210,
                'This is a long string that goes on'],
            'more': { {'inner': 'This whole logical line should be wrapped.', some_tuple: [1,
                                                                                           20, 300, 40000, 500000000, 60000000000000000]}}
        return (some_tuple, some_variable)

    def example2(): return ('' in {'f': 2}) in {'has_key() is deprecated': True}

    class Example3(object):

        def __init__(self, bar):
            # Comments should have a space after the hash.
            if bar:
                bar += 1
                bar = bar * bar
                return bar
            else:
                some_string = """
    		           Indentation in multiline strings should not be touched.
    Only actual code should be reindented.
    """
                return (sys.path, some_string)

Specifically the 2 lines before the return in example1(). Any thoughts?

**Comment by myint** [comment]
Not sure. I think I need more [information](https://github.com/hhatto/autopep8/blob/master/CONTRIBUTING.rst).

**Comment by DavidSnider** [comment]
Ah, I apologize.

`$ autopep8 --version`
autopep8 0.9.1

`$ pep8 --version`
1.4.6

`$ python --version`
Python 2.7.6

`$ uname -a`
Linux me 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

For reference, I installed autopep8 and pep8 today through 

`sudo apt-get install ...`

**Comment by myint** [comment]
I think your version of `pep8` is too old. The latest version is [1.6.2](https://github.com/jcrocholl/pep8).

**Comment by DavidSnider** [comment]
Ah I see that. By any chance do you know if it's possible to upgrade to those versions on linux? 

If not, feel free to close. Thanks!

**Comment by myint** [comment]
https://github.com/hhatto/autopep8#installation
