### ISSUE TITLE
'E713' is not being fixed by autopep8

### ISSUE THREAD

**Issue by mbanders** [hhatto/autopep8#209]
Example file:

```python
if not "pup" in "kitten":
    print("Hi")
```

pep8 finds E713, which is true:
```sh
$ pep8 example.py
example.py:1:4: E713 test for membership should be 'not in'
```

Then I run `autopep8` on it, but it doesn't fix it:
```sh
$ ./autopep8.py --version
autopep8 1.2a0

$ ./autopep8.py example.py
if not "pup" in "kitten":
    print("Hi")
```

Even selecting for it, it doesn't fix:
```sh
$ ./autopep8.py example.py --select E713
if not "pup" in "kitten":
    print("Hi")
```

**Comment by myint** [comment]
Yeah, autopep8 only handles the trivial case.

https://github.com/hhatto/autopep8/blob/16ce532e03a2787e14380b642688efac1d19d642/autopep8.py#L975
