### ISSUE TITLE
--indent-size option doesn't apply to dictionaries, lists and tuples

### ISSUE THREAD

**Issue by PLPeeters** [hhatto/autopep8#213]
The `--indent-size` option doesn't seem to apply to dictionaries, lists and tuples. Here's some example input:

```
[
        'foo',
        'bar'
]

{
        'foo': 'bar',
        'baz': 42
}

(
        1,
        2,
        3
)

def test():
        pass
```

Running `autopep8 --indent-size 8` on the input above processes the following result:

```
[
    'foo',
    'bar'
]

{
    'foo': 'bar',
    'baz': 42
}

(
    1,
    2,
    3
)


def test():
        pass
```

As you can see, the indentation on the dictionary, the tuple and the list was corrected to 4 spaces despite the `--indent-size` option being set to `8`. I wanted to submit a PR, but I couldn't find the part of the code which takes care of this.

**Comment by PLPeeters** [comment]
Is there anything planned regarding this? It really prevents me from using AutoPEP8 as I have to go over the code again to reindent all dictionaries, lists and tuples correctly. If this wasn't necessary, I'd use it as a Git pre-commit hook, which would be truly awesome.

Again, I'd happily submit a pull request for this if someone could tell me which part of the code handles this. I've tried reading through it multiple times but couldn't figure it out.

**Comment by myint** [comment]
You might want to take a look at yapf for formatting to non-PEP8 styles.

**Comment by PLPeeters** [comment]
Having an indent-size option is already non-PEP8, since PEP8 clearly states lines should be indented by 4 spaces. As such, since there's an option to increase the indent size already, I believe it should apply to everything, including dictionaries, etc. No editor is going to convert a tab to _n_ spaces if it's in front of a normal line and to _n/2_ spaces if it's in front of a dictionary/tuple/list indent, which is why I am suggesting this.

**Comment by PLPeeters** [comment]
I will check out yapf, though :)

**Comment by myint** [comment]
Just out of curiosity, why do you prefer 8 spaces over 4?

**Comment by PLPeeters** [comment]
I _really_ don't, but for some reason that's what they use at work because Vim is configured with 8 spaces as indention by default...
