### ISSUE TITLE
Checking more than just 1 file

### ISSUE THREAD

**Issue by voarsh** [hhatto/autopep8#215]
Hi.

I am not sure if I am being daft, but is there a way to check more than one filename? Say a folder within a module(s)? Or an entire directory with many modules and directories?

**Comment by myint** [comment]
Yes there is, please see `--recursive` in `--help`.

**Comment by voarsh** [comment]
Ah! Sorry about that! I just saw that a few minutes ago!
Thanks, it works wonderfully. :)  ^^
