### ISSUE TITLE
Fix E225?

### ISSUE THREAD

**Issue by ChillarAnand** [hhatto/autopep8#219]
Looks like autopep8 is  not fixing E225, it would be great if it can fix that too.

**Comment by myint** [comment]
Could you provide a test case?

Thanks

**Comment by ChillarAnand** [comment]
```
$ cat test.py
x = 'foo'[0:  2]

$ autopep8 test.py 
x = 'foo'[0:  2]
```

**Comment by myint** [comment]
Does `pep8` flag that? (If not, this needs to be brought up in their issue tracker.)

**Comment by ChillarAnand** [comment]
Thanks @myint
