### ISSUE TITLE
E122 not fixed

### ISSUE THREAD

**Issue by balasankarc** [hhatto/autopep8#222]
Hi,

autopep8 doesn't seem to fix E122 issues for me. See the log below

$ cat pep8_test.py 
```
a = tackle(sample, 'test1',
        {
            'a': sample,
            'b': testing
            }
        )
```
$ autopep8 --aggressive --aggressive --aggressive pep8_test.py > pep8_test2.py
$ cat pep8_test2.py 
```
a = tackle(sample, 'test1',
           {
           'a': sample,
           'b': testing
           }
           )
```
$ pep8 pep8_test2.py 
```
pep8_test2.py:3:12: E122 continuation line missing indentation or outdented
pep8_test2.py:4:12: E122 continuation line missing indentation or outdented
```

**Comment by myint** [comment]
I don't seem to see that problem. `autopep8 -aaa` gives me:

```python
a = tackle(sample, 'test1',
           {
               'a': sample,
               'b': testing
           }
           )
```

Please see the following link.
https://github.com/hhatto/autopep8/blob/master/CONTRIBUTING.rst#issues

**Comment by balasankarc** [comment]
I am extremely sorry. It was an issue with autopep8 version I was using. I purged the old version and it works fine now. Sorry for the inconvenience caused.
