### ISSUE TITLE
Is it possible to mark line to exclude it from autocorrection?

### ISSUE THREAD

**Issue by xliiv** [hhatto/autopep8#223]
Like the topic, let's say i've got a line in my code which is marked as `# noqa`.
I'd like to exclude such lines from autocorrection.

**Comment by myint** [comment]
I think it is dependent on what `pep8` supports. `pep8` supports `noqa` for some error codes, I think.

**Comment by xliiv** [comment]
I made this line (for test purpose):

```
####some_var = 3  #noqa
```

Then i ran autopep8 and the result was:

```
# some_var = 3  #noqa
```

I'd expect this line won't be touched, instead of that it was corrected.
