### ISSUE TITLE
does not retain original newline char on windows

### ISSUE THREAD

**Issue by s-trooper** [hhatto/autopep8#224]
Hi, 
because of ```sys.stdout``` standard windows behavior for the '\n' the original newline char, in my case LF was not preserved. The fix i found is to add code bellow:
```py
if sys.platform == 'win32': 
    import os, msvcrt
    msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)
```

P.S: 
the command i using is```autopep8 file1.py > file1_tmp.py```
on windows 7 with python 2.7.10 and autopep8 (1.2.1)

**Comment by myint** [comment]
If you want to preserve line endings, it might be best to use the `--in-place` option. (You can copy the file beforehand if you want to keep the original file too.)
