### ISSUE TITLE
--ignore W293 not working

### ISSUE THREAD

**Issue by shadowwalkersb** [hhatto/autopep8#230]
Seems like W293 is not ignored when used as follows,
`--ignore W293`
`--ignore W29`
`--ignore W2`
`--ignore W`

**Comment by shadowwalkersb** [comment]
Seems to have attracted a lot of attention! Closing to avoid unnecessary clutter.

**Comment by eyeonus** [comment]
So, this still isn't fixed, then? That's unfortunate.
