### ISSUE TITLE
Is autopep8 safe to use on a large codebase?

### ISSUE THREAD

**Issue by ZzAntares** [hhatto/autopep8#234]
Hi, I'm working in quite a big django project (aprox 36867 lines of code), I'm in charge of setup a building process for the project (run the tests, generate coverage, etc) and I would like to run `autopep8` on each commit automatically.

Since I want to have the repo in a clean state I want to run autopep8 in all my codebase, but since is a big project and our tests only cover 50% of the actual code I'm afraid autopep8 will break some code.

My question is, is really safe to use `autopep8`? (assuming `--aggressive` flag is not used)

Thanks in advance and sorry for my mistrust.

**Comment by myint** [comment]
Yes, it is safe (without `--aggressive`). It that mode it will only modify whitespace.

We regularly test that this is the case in our [`acid test`](https://github.com/hhatto/autopep8/blob/master/test/acid.py), which runs `autopep8` against suites of files and verifies that the resulting syntax is correct and that the program stays the same. The latter is checked by checking that the compiled bytecode remains identical.

**Comment by ZzAntares** [comment]
Wow, thanks! I'll go ahead and setup autopep8 on my build now.

Thanks!
