### ISSUE TITLE
windows: failed to create process

### ISSUE THREAD

**Issue by Chiel92** [hhatto/autopep8#239]
When trying to run autopep8 on windows, from either git bash or cmd prompt, it just says 

```bash
$ autopep8 --help
failed to create process.
```

I'm on windows 7, using autopep8 (1.2.2).

**Comment by myint** [comment]
Could this be like #226?

**Comment by Chiel92** [comment]
Dammit, yes. Wasn't able to find it through google easily. Solution posted there works.
