### ISSUE TITLE
bug in W690 formatting

### ISSUE THREAD

**Issue by bagerard** [hhatto/autopep8#240]
Hi there,

It's minor but the following line:
`time.sleep(01)`

is altered as
`time.sleep(0o1)`

after I run autopep8 with the following arguments: "--aggressive --in-place --select=W690 "

**Comment by Digenis** [comment]
Not a bug; this is exactly what autopep8 is supposed to do here.
Python3 requires octal representations to be written that way.
https://www.python.org/dev/peps/pep-3127/#removal-of-old-octal-syntax

**Comment by bagerard** [comment]
Alright, in my case "01"  was a typo and I thought it would be changed to "1" but I understand now.
Thanks!
