### ISSUE TITLE
Formatting non-python files

### ISSUE THREAD

**Issue by GMNGeoffrey** [hhatto/autopep8#245]
I have cProfile outputs in my directory and autopep8 is trying to format them. I think this is not intended behavior.

**Comment by myint** [comment]
I can't seem to reproduce this behavior. Could you provide an example?

Thanks

**Comment by GMNGeoffrey** [comment]
Ok I think I know what the issue was. I was using `autopep8 -ivr *` instead of `autopep8 -ivr .`
The latter does what I want. So I guess autopep8 does format a file if you specifically give it that file, which I suppose makes sense :-) I think I would make the default to ignore non-python files anyway and have a flag to not do that check, but nbd.
