### ISSUE TITLE
Check that docstrings are triple-double-quotes

### ISSUE THREAD

**Issue by mairsbw** [hhatto/autopep8#247]
There are many guidelines proposed within the [PEP257](https://www.python.org/dev/peps/pep-0257/) document. One of the easiest ones to check is that docstrings should always use triple-double-quotes """.

I don't know if this is out of scope for this module (since it's names `autopep8`), but I think a lot of the guidelines proposed in PEP257 would be nice additions to this program.

**Comment by myint** [comment]
In terms of checking PEP 257, there is [`pycodestyle`](https://github.com/PyCQA/pydocstyle). For formatting, there is [`docformatter`](https://github.com/myint/docformatter).
