### ISSUE TITLE
Autopep8 does not add a space after # for inline comments

### ISSUE THREAD

**Issue by graipher** [hhatto/autopep8#255]
This linter complaint:

$ pep8 test.py
test.py:52:5: E265 block comment should start with '# '

is not being fixed by:
$ autopep8 test.py
...
#h,f = histogram(data)
...

**Comment by myint** [comment]
This is intentional. Several people asked us to ignore commented-out code in the past. (In my opinion, it is probably better to just delete those lines.)

https://github.com/hhatto/autopep8#features

> `E265`, which refers to spacing after comment hash, is ignored if the comment looks like code. autopep8 avoids modifying these since they are not real comments. If you really want to get rid of the pycodestyle warning, consider just removing the commented-out code. (This can be automated via [eradicate](https://github.com/myint/eradicate).)

**Comment by graipher** [comment]
OK, thanks for the feedback. I guess I can live without those spaces.
