### ISSUE TITLE
maxint → maxsize fails

### ISSUE THREAD

**Issue by spaceone** [hhatto/autopep8#265]
```
$ cat /tmp/maxint.txt 
from sys import maxint
maxint
$ ~/autopep8.py -aaa /tmp/maxint.txt
from sys import maxsize
maxint
```
→ maxint references are not replaced

**Comment by hhatto** [comment]
use with `--ignore=W690` option.

```
$ autopep8 -aaa --ignore=W690 mi.py
from sys import maxint
maxint
```

**Comment by spaceone** [comment]
@hhatto Sorry, but did you look exactly at the issue? The autopep8-code makes the code broken if maxint is imported from sys. Everything is fine when always using sys.maxint. Autopep8 should not replace "from sys import maxint" (or alternatively replace all maxint references).
