### ISSUE TITLE
E713 regression

### ISSUE THREAD

**Issue by spaceone** [hhatto/autopep8#276]
A regression caused by https://github.com/hhatto/autopep8/issues/262 was introduced which breaks code:
The following diff is generated:
-»   if '@' not in foldername or not '/' in foldername:
+»   if '@' in foldername or not '/' not in foldername:

**Comment by hhatto** [comment]
Thanks for reporting.

fix in latest master c380e2e40ff807b066832e32d09be05839e75a72
