### ISSUE TITLE
Question: fix only files in subfolders with keyword in the path name 

### ISSUE THREAD

**Issue by antonioj-mattos** [hhatto/autopep8#290]
Is there a way to set the tool to only fix files in paths which contain a specific word?

For instance, I am working with a legacy code base which I am not supposed to mess with old stuff, but I have new code being added on sub-folders all starting with "keyword". So I'd like autopep8 to only fix the files inside the many "keyword" sub-folders inside the project.

I know I could run the tool with a specific path, but I'd like it to run automatically on every save, and have it setup in a configuration file, so that everyone in the project could use it transparently.

**Comment by spaceone** [comment]
You can pass the files as arguments. On the linux CLI tool you can for example use:
`autopep8 -i -- $(find -name '*myword*.py')`

**Comment by antonioj-mattos** [comment]
@spaceone that will suffice for now. 

I will try to figure it out how to configure to work directly with the editor settings. I use VSCode with a configuration similar to:

```json
    "python.formatting.provider": "autopep8",
    "python.formatting.autopep8Args": [
        "--max-line-length=119"
    ],
    "python.formatting.formatOnSave": true
```

In this case, it is more a matter to deal with the vscode plugin.

Thank you.
