### ISSUE TITLE
Installed on VSCODE and it doesn't do anything on current file

### ISSUE THREAD

**Issue by ANTGOMEZ** [hhatto/autopep8#291]
Installed autopep per instructions.

I select the file I want to clean up, then ctrl-shft-p and select autopep8

Result: nothing happens to the file. Error says the autopep command is not recognized or does not exist.

**Comment by myint** [comment]
I'm not familiar with VS Code, but I think you need to report this to whoever maintains the autopep8 plugin for VS Code.

**Comment by ANTGOMEZ** [comment]
Figured it out. The vscode autopep plugin doesn't install autopep. had to install autopep separately through pip.

**Comment by myint** [comment]
Good to hear!
