### ISSUE TITLE
Improve E731 fix.

### ISSUE THREAD

**Issue by stepshal** [hhatto/autopep8#298]
1. Support fix for lines like this: 
```py
f = lambda: 2*x
```
Into:
```py
def f():
         return 2*x
```

2. Current fix creates another multiple warnings:
```py
def f(x): return 2*x
```
Such as E704,E271, E128 and E306 if there two lamba assignment together.
So It's should be:
```py
def f(x): 
      return 2*x 
```

**Comment by spaceone** [comment]
This is https://github.com/hhatto/autopep8/issues/277 and https://github.com/hhatto/autopep8/issues/279 and https://github.com/hhatto/autopep8/issues/278

**Comment by stepshal** [comment]
Oh, sorry.
