### ISSUE TITLE
Support for PEP526 for Python 3.6

### ISSUE THREAD

**Issue by orenbenkiki** [hhatto/autopep8#299]
Currently, `autopep8` does not support Python 3.6 (specifically, PEP526): given `a: Optional[int] = 7` it will break the line after `a:` and place the `Optional[int] = 7` in a following indented line.

Is there an ETA for Python 3.6 support?

**Comment by hhatto** [comment]
fix in ce1de73cccce73c5784bfb4a411066d2f76a447c

**Comment by orenbenkiki** [comment]
Awesome! So I guess in https://pypi.python.org/pypi/autopep8 in 1.2.5 it will be marked as compatible with 3.6 (assuming the next version going to be 1.2.5)?

**Comment by hhatto** [comment]
I'm planning to release version 1.3 containing several bug fixes next week.

**Comment by orenbenkiki** [comment]
Great news - thanks!
