### ISSUE TITLE
autopep8 cannot be run recursively on a directory structure

### ISSUE THREAD

**Issue by ssbarnea** [hhatto/autopep8#30]
autopep8 cannot be run recursively on a directory structure

**Comment by Avasam** [comment]
Recursive does not work for me either.
Works: `autopep8 $(git ls-files '**.py*') --in-place`
Does not: `autopep8 src/ typings/ --recursive --in-place`
No error message

**Comment by kehrazy** [comment]
For Windows:

```batch
for /r %v in (*.py) do autopep8 --in-place %v
```
