### ISSUE TITLE
Google Summer of Code

### ISSUE THREAD

**Issue by sils** [hhatto/autopep8#301]
Hey @myint and @hhatto specifically as you're listed as package owner on PyPI.

[coala](https://coala.io) will most likely participate in GSoC this year. [We are using autopep8](https://github.com/coala/bear-docs/blob/master/docs/PEP8Bear.rst) to power part of the python code analysis we offer in coala.

Now here's the thing: would you, i.e. autopep8, be willing to take on a GSoC student we might be able to get you one, functioning as an umbrella organization.

## How it works

- You define a project with us.
- You provide at least one mentor, two ideally. 
- One member of coala will be paid for administering coala, that includes:
    - helping you making a great idea
    - helping you with any problems you might have
    - checking up on all students, finding out if mentors fail to do so themselves :)

## Why do it

- You get a student that works on your project, ideally sticks with your project long term
- You don't have to bother about the admin work
- Our communities can share knowledge

## Why we do it

- We get better integration of your tool
- We get upstream improvements
- We get another student, google likes umbrella orgs as they are their chance to pull in more small projects like you
- Our communities can share knowledge

Does this sound interesting to you? We will submit the initial application somewhen tomorrow, the deadline is later. However **we need to know if this is going to happen within the next week sharp.**

**Comment by sils** [comment]
Oh CC @sims1253 and @jayvdb from coala

**Comment by myint** [comment]
I haven't been heavily involved in autopep8 development recently (mainly due to not needing to frequently reformat large amounts of legacy Python code anymore). I don't have enough interest to come up with a an interesting project for a student.

I'm willing to help review code and guide the student if someone else like @hhatto decides to come up with a project for the student.

**Comment by sils** [comment]
So one idea about a project for autopep8 would be to preserve the information which change is associated with which errors/warnings (see https://github.com/hhatto/autopep8/issues/289), a lot of coala users complain about our PEP8Bear (that is scheduled for being renamed to AutoPEP8Bear) that it only fixes the issues but doesn't tell them for every issue, what it actually is about.

I would imagine a JSON output like:

```json
{
    "error": "E251",
    "message": "Remove whitespace around '=' sign.",
    "diff": [
         {"line": 4, "new_content": "a = function(test='a')"}
    ]
}
```

or anything like that allowing the users to see the reason for every single change.

Your own ideas are very much possible as well of course,this is just one thing we thought about.

**Comment by hhatto** [comment]
@sils 
This proposal is interesting, but it is not likely to cooperate. I can not have enough time for this project, and English communication is very difficult for me :-|

Sorry, I couldn't help you.

Patches are always welcome:-)
