### ISSUE TITLE
The Readme Doesn't Mention E11* Codes

### ISSUE THREAD

**Issue by lekv** [hhatto/autopep8#302]
The readme file doesn't reference the E11* codes from pycodestyle, but they are still effective. I'm not familiar enough with the different code systems to suggest a correction, but if someone points out the error, I'd be happy to create a fix and submit a PR.

**Comment by hhatto** [comment]
Is it insufficient with the following description?

* https://github.com/hhatto/autopep8/blame/master/README.rst#L181
* https://github.com/hhatto/autopep8/blame/master/README.rst#L241-L242

If it is insufficient, please pull-request. Thanks :-)
