### ISSUE TITLE
Support for W292

### ISSUE THREAD

**Issue by ickedude** [hhatto/autopep8#303]
W292: no newline at end of file

autopep8 actual behavior:
```bash
$ printf 'example' | autopep8 -
example
```
actual pycodestyle behavior:
```bash
$ printf 'example' | pep8 -
stdin:1:8: W292 no newline at end of file
```
correct example:
```bash
$ printf 'example\n' | pep8 -
```

Why: Per [POSIX definition](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) a line of a text file need to end with a newline. Even if PEP8 does not require, most IDEs forces a new line at the end of file. If autopep8 does not, you always have unnecessary diff noise.

**Comment by myint** [comment]
```
$ echo -n 'import x' > foo.py

$ file foo.py
foo.py: ASCII text, with no line terminators

$ ./autopep8.py --diff foo.py
--- original/foo.py
+++ fixed/foo.py
@@ -1 +1 @@
-import x
\ No newline at end of file
+import x

$ ./autopep8.py -i foo.py

$ file foo.py
foo.py: ASCII text
```

**Comment by ickedude** [comment]
You are right, my example was not complete. Sorry for that. I also test Windows line ending and it is working.
```bash
$ printf 'example\nexample2' | unix2dos | pep8 -
stdin:2:9: W292 no newline at end of file
$ printf 'example\nexample2' | unix2dos | autopep8 - | hexdump -C
00000000  65 78 61 6d 70 6c 65 0d  0a 65 78 61 6d 70 6c 65  |example..example|
00000010  32 0d 0a                                          |2..|
00000013
```
So maybe the feature list can be extended to also list W292?
