### ISSUE TITLE
autopep8 mangled (silly) one line function

### ISSUE THREAD

**Issue by tholom** [hhatto/autopep8#316]
```def one_liner_with_several_commands(arg): do_summat(arg); summat_else(arg)```

becomes:

```def one_liner_with_several_commands(arg): do_summat(arg)```

```summat_else(arg)```

which can (and did) actually parse as valid python, but obviously screws up the sense.

**Comment by spaceone** [comment]
You can use 3 backticks for the styling here.

**Comment by tholom** [comment]
Fixed. Thanks!

**Comment by spaceone** [comment]
@myint You didn't fix this but only added a workaround that this bug doesn't happen. Autopep8 should form this properly into the new line.

**Comment by jayvdb** [comment]
Create a new issue for reformatting multi-statement lines?

My guess is that lambda's make a proper fix quite non-trivial.

**Comment by myint** [comment]
I think it fixes this specific issue of mangling the code. Feel free to open a new issue as @jayvdb suggested.
