### ISSUE TITLE
BaseException error

### ISSUE THREAD

**Issue by 3xp10it** [hhatto/autopep8#320]
Hi,I used autopep8 today and something seems wrong about `BaseExeception`.
I have a file `1.py` with below content:
```
import os
a=1
try:
    print(1)
    os.system("lala")
except:
    if a==1:
        print("ok")
        os.system("ls")
        print(2)
    elif a==2:
        print("not ok")
```

I want to use autopep8 to make it more beautiful,then I run:
`autopep8 -a -a -i 1.py`

then I get the new `1.py` with below content:

```
import os
a = 1
try:
    print(1)
    os.system("lala")
except BaseException: if a == 1:
        print("ok")
        os.system("ls")
        print(2)
    elif a ==2:
        print("not ok")
```

upon change by autopep8 is wrong coz I got below error by run:

`python3 1.py`
error detail:
``` 
 File "1.py", line 6
    except BaseException: if a == 1:
                           ^
SyntaxError: invalid syntax
```

Can you help me?

**Comment by hhatto** [comment]
Thank you for reporting bug.

fix in latest master 3ad6751182bff5105fd07151f399b856ddaaa140
