### ISSUE TITLE
Incorrectly removes valid whitespace

### ISSUE THREAD

**Issue by benf-wspdigital** [hhatto/autopep8#322]
The U+000C FORM FEED character [is valid white space](https://docs.python.org/3/reference/lexical_analysis.html#blank-lines). A line containing only U+000C at the end of a line [is a valid blank line for Python](https://docs.python.org/3/reference/lexical_analysis.html#indentation)::

```
$ printf "print('hello')\n\f\nprint('python')\n" > foo.py

$ wc foo.py
       3       2      33 foo.py

$ pycodestyle foo.py

$ python3 ./foo.py
hello
python
```

The `autopep8` behaviour removes the valid whitespace::

```
$ autopep8 foo.py > foo.py.autopep8

$ wc foo.py.autopep8 
       3       2      32 foo.py.autopep8

$ grep -c '\f$' foo.py foo.py.autopep8 
foo.py:1
foo.py.autopep8:0
```

The `pycodestyle` tool correctly does *not* consider the U+000C character a trailing white space character (the W291 warning is not triggered).

So the `autopep8` tool should also not remove that valid character from the line.

**Comment by hhatto** [comment]
@benf-wspdigital 
Thanks for reporting 👍 

fix in #376.
