### ISSUE TITLE
Not following PEP8 Whitespace in Expressions and Statements

### ISSUE THREAD

**Issue by sbienkow** [hhatto/autopep8#330]
autopep8 --version: 1.3.1
pycodestyle --version: 2.3.1
python --version: 3.6.1

It converts this
```
x = x*2 - 1
hypot2 = x*x + y*y
c = (a+b) * (a-b)
```
to this
```
x = x * 2 - 1
hypot2 = x * x + y * y
c = (a + b) * (a - b)
```
which is against PEP8.
[Source](http://pep8.org/#other-recommendations)

**Comment by hhatto** [comment]
Thank you for reporting.

fix in latest master (3b9945e3ed03e9cfc81336f1deb0412a03df8a9d)
