### ISSUE TITLE
--max-line-length can't work?

### ISSUE THREAD

**Issue by tsaizehua** [hhatto/autopep8#331]
Hello, after "autopep8 --in-place --aggressive --aggressive --max-line-length=100", everything is nice but the line is still over 100 characters (Even exclude the space indent, https://github.com/hhatto/autopep8/issues/253).

**before:**
```
    if (arg_hour_beg <= action_time <= arg_hour_end) or (event_day == arg_date_target and (2015080500 <= action_time <= arg_hour_2daysago)):
```
**after:**
```
    if (arg_hour_beg <= action_time <= arg_hour_end) or (event_day ==
                                                         arg_date_target and (2015080500 <= action_time <= arg_hour_2daysago)):
````

**or nothing change:**
```
print "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s" % ("TAG_101", platform, version, action_id, '/', '/', '/', str_val, use_times, uid)
```

thank you :)

**Comment by hhatto** [comment]
@tsaizehua 
Thanks for reporting.

fixed by #355, closing. Feel free to reopen if needed.
