### ISSUE TITLE
E133 is not supported

### ISSUE THREAD

**Issue by brianbruggeman** [hhatto/autopep8#339]
Long story short, this is now being enforced on the project I am working on, and going through all of the files I've written to make sure they're compliant and pass peer review:  is tedious at best.

Any thought on how to add E133?

[E133](http://pep8.readthedocs.io/en/release-1.7.x/intro.html#error-codes):  closing bracket is missing indentation

More or less, this code:

     x = {
         'key': value,
     }

Must become:
   
     x = {
         'key': value,
         }

It's pretty gruesome looking for pytest parametrize or any longer/deep data structure.

**Comment by hhatto** [comment]
E133 fixed method is implemented in 4c10e91219e8c6f617afe14678d778fcbb382777.

usage:
```
$ autopep8 --hang-closing TARGET.py
```

Thanks
