### ISSUE TITLE
Function annotations with defaults are incorrectly changed

### ISSUE THREAD

**Issue by vdboor** [hhatto/autopep8#340]
PEP 484 changes function annotations to include spaces.

Thus, the following syntax is correct:

```
def foo(value: Optional[str] = None):
    pass
```

autopep8 wants to remove the extra spaces however:

```
def foo(value: Optional[str]=None):
    pass
```

**Comment by webjunkie** [comment]
For me it doesn't do anything, though I would it to change it to have spaces in every occurrence.

**Comment by hhatto** [comment]
It is not recommended in PEP 8.
https://www.python.org/dev/peps/pep-0008/#other-recommendations

> When combining an argument annotation with a default value, use spaces around the = sign (but only for those arguments that have both an annotation and a default).
> 
> Yes:
> 
> def munge(sep: AnyStr = None): ...
> def munge(input: AnyStr, sep: AnyStr = None, limit=1000): ...
> No:
> 
> def munge(input: AnyStr=None): ...
> def munge(input: AnyStr, limit = 1000): ...

I also do not point out pycodestyle.

**Comment by jayvdb** [comment]
With https://github.com/PyCQA/pycodestyle/issues/692 fixed, presumably this enhancement to autopep8 can now be done.
