### ISSUE TITLE
Visual Studio Code for OSX does not find autopep8

### ISSUE THREAD

**Issue by danquack** [hhatto/autopep8#349]
Not sure if this is a bug for anyone else, or for visual studio code, but upon pip install autopep8 is not detected. Manual entry of bin path doesn't allow for formatting. Formatting does work in the CLI.

**Comment by hhatto** [comment]
@danquack 
Could you please describe the information a little more?

Are you using [pythonVSCode](https://github.com/DonJayamanne/pythonVSCode)?

**Comment by danquack** [comment]
I am not using pythonVSCode. I downloaded the package straight from VS Studio marketplace. Then I tried pip installation. When I make a manual entry into the config for autopep8 and then do a >format nothing happens.

**Comment by hhatto** [comment]
Could you ask a question in Visual Studio Code community?
https://code.visualstudio.com/community/

**Comment by danquack** [comment]
Opened up a stack, but I think this is related to autopep8 itself. Link to stack: https://stackoverflow.com/questions/35533052/changing-theme-of-suggestion-drop-down-container

**Comment by jayvdb** [comment]
> I downloaded the package straight from VS Studio marketplace

Which package?

This repo doesnt publish anything into the VS Studio marketplace, so it is likely that you are downloading an addon created by someone else.

**Comment by Sybrand** [comment]
`brew install autopep8`

Fixed it for me.

**Comment by hhatto** [comment]
Thank you for using autopep8.
But, this is not autopep8's issue.
