### ISSUE TITLE
E702 fixes code incorrectly

### ISSUE THREAD

**Issue by ancc** [hhatto/autopep8#364]
autopep8 version 1.3.3
With following code:
```
for i in range(3):
    if i == 1: print i;continue
    print i
```

output is:
0
1
2

after running
autopep8 -i --select=E702

code will be

```
for i in range(3):
    if i == 1: print i
    continue
    print i
```

and output is
1

correct is

```
for i in range(3):
    if i == 1: print i
        continue
    print i
```

**Comment by hhatto** [comment]
Thanks for reporting.

```
for i in range(3):
    if i == 1: print i
        continue
    print i
```
this is invalid python code.

As one of the suggested solutions to prevent and correct if there is the same line E701 and E702.

**Comment by hhatto** [comment]
fix in latest master.

We will be releasing version 1.5.2 with this fix in next week.

Thanks
