### ISSUE TITLE
[Errno 13] Permission denied: 'project path'

### ISSUE THREAD

**Issue by Matuiss2** [hhatto/autopep8#377]
Im receiving this error (on some of mine projects, not all which make this even more annoying) while trying to use autopep8 on pycharm. Anyone knows how to fix it?

**Comment by jayvdb** [comment]
Sounds like a problem with how pycharm is configured to use autopep8.  Maybe there is a literal `project path` in the command line which needs to be replaced with a variable provided by pycharm.

**Comment by hhatto** [comment]
Thank you for using autopep8.

But, this is not autopep8's issue.

Thanks.

**Comment by guxiaoyong** [comment]
Try add parameter '--recursive', this works for me.
