### ISSUE TITLE
Help - How to use local config file?

### ISSUE THREAD

**Issue by michaelfresco** [hhatto/autopep8#378]
I don't understand how to use a local config to pass settings to. For example, with flake8 you can have a `.flake8` file which you dump in your project root, and pass settings to like [this](http://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations):

    [flake8]
    # ignore = D203
    max-line-length = 99

How can I do the same with autopep8?

**Comment by abendebury** [comment]
Try moving `.flake8` to `setup.cfg` and using the pycodestyle configuration.

https://pycodestyle.readthedocs.io/en/latest/intro.html#configuration

**Comment by DollarAkshay** [comment]
@michaelfresco Just replace `[flake8]` with `[pep8]`
