### ISSUE TITLE
can't run autopep8 directly after pip installed it

### ISSUE THREAD

**Issue by GraceGay** [hhatto/autopep8#379]
uninstall the package
haijun@Blackhole:~/ws/frame/concept$ pip uninstall autopep8
Uninstalling autopep8-1.3.4:
  /home/haijun/.local/bin/autopep8
  /home/haijun/.local/lib/python2.7/site-packages/autopep8-1.3.4.dist-info/DESCRIPTION.rst
  /home/haijun/.local/lib/python2.7/site-packages/autopep8-1.3.4.dist-info/INSTALLER
  /home/haijun/.local/lib/python2.7/site-packages/autopep8-1.3.4.dist-info/METADATA
  /home/haijun/.local/lib/python2.7/site-packages/autopep8-1.3.4.dist-info/RECORD
  /home/haijun/.local/lib/python2.7/site-packages/autopep8-1.3.4.dist-info/WHEEL
  /home/haijun/.local/lib/python2.7/site-packages/autopep8-1.3.4.dist-info/entry_points.txt
  /home/haijun/.local/lib/python2.7/site-packages/autopep8-1.3.4.dist-info/metadata.json
  /home/haijun/.local/lib/python2.7/site-packages/autopep8-1.3.4.dist-info/top_level.txt
  /home/haijun/.local/lib/python2.7/site-packages/autopep8.py
  /home/haijun/.local/lib/python2.7/site-packages/autopep8.pyc
Proceed (y/n)? y
  Successfully uninstalled autopep8-1.3.4
haijun@Blackhole:~/ws/frame/concept$ pip3 uninstall autopep8
Uninstalling autopep8-1.3.4:
  /home/haijun/.local/lib/python3.5/site-packages/__pycache__/autopep8.cpython-35.pyc
  /home/haijun/.local/lib/python3.5/site-packages/autopep8-1.3.4-py3.5.egg-info
  /home/haijun/.local/lib/python3.5/site-packages/autopep8.py
Proceed (y/n)? y
  Successfully uninstalled autopep8-1.3.4
Reinstall:
haijun@Blackhole:~/ws/frame/concept$ pip3 install autopep8 --user -I
Collecting autopep8
Collecting pycodestyle>=2.3 (from autopep8)
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Installing collected packages: pycodestyle, autopep8
Successfully installed autopep8-1.3.4 pycodestyle-2.3.1

haijun@Blackhole:~/ws/frame/concept$ pip install autopep8 --user -I
Collecting autopep8
Collecting pycodestyle>=2.3 (from autopep8)
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Installing collected packages: pycodestyle, autopep8
Successfully installed autopep8-1.3.4 pycodestyle-2.3.1
haijun@Blackhole:~/ws/frame/concept$ python --version
Python 2.7.12

haijun@Blackhole:~/ws/frame/concept$ autopep8
The program 'autopep8' is currently not installed. To run 'autopep8' please ask your administrator to install the package 'python-autopep8'
haijun@Blackhole:~/ws/frame/concept$ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
 
Why I still can not run the auropep8 directly?

**Comment by jayvdb** [comment]
`/home/haijun/.local/bin` is probably not in your `PATH`.
