### ISSUE TITLE
Autoformat of boolean equality comparison to True/False could change semantics

### ISSUE THREAD

**Issue by mossberg** [hhatto/autopep8#382]
Hi! Apologies if this is not the correct place for this discussion, but I wanted to inform you about an issue we (https://github.com/trailofbits/manticore) had recently, related to autopep8, that you might want to take into consideration. It is not _necessarily_ a bug.

autopep8 will simplify boolean equality comparisons to a True/False literal, e.g.

`var == True` will be formatted to just `var`. However, if `var` is an object which overloads the `==` operator, this autoformat could result in changed semantics for the autoformatted program, depending on the `__eq__` overloading function.

Specifically for our use case, we use this style of operator overloading to conveniently create AST-like expression tree data structures. For example, `var == True`, would return an `EqualExpression` object. With the autoformat, this would be simplified to just `var`, which would be incorrect in the context of our project.

Due to the fact that this autoformat can sometimes cause bugs in the formatted program, perhaps we could consider not enabling this autoformat by default?

**Comment by myint** [comment]
I think I agree with this. Though, it looks like `E711` and `E712` are already disabled by default. The `--aggressive` option enables it.

https://github.com/hhatto/autopep8/blob/81d90c3dbb307a5c0c649c41f1bb1ada3c874f4e/autopep8.py#L1607

**Comment by mossberg** [comment]
ah right, our fault. thanks!
