### ISSUE TITLE
"not" moved to wrong "in"

### ISSUE THREAD

**Issue by fordvision** [hhatto/autopep8#388]
With 2x aggressive "-a -a"

-    if not 'results' in response and 'message' in response:

get rewritten to:

+    if 'results' in response and 'message' not in response:

```python
>>> response = {1,2}
>>> if not 3 in response and 2 in response:
...   print True
True
>>> if 3 in response and 2 not in response:
...   print True
>>> if 3 not in response and 2 in response:
...   print True
True
```

**Comment by hhatto** [comment]
thank you for reporting.

fix in #390.
autopep8 version 1.3.5 has been released.

Thanks.
