### ISSUE TITLE
Implicit line breaks within parentheses vs. operators vs. comments 

### ISSUE THREAD

**Issue by bersbersbers** [hhatto/autopep8#392]
I do not know how to summarize this briefly, comprehensive, and correctly.

Non-comprehensively: autopep8 creates improper syntax. Here's an example:

test.txt
```
X = (
    1  # 1
    + 2  # 2
    + 3  # 3
    + 4  # 4
    + 5  # 5
    + 6  # 6
    + 7  # 7
)
```

And this is the output:

```
C:\>autopep8 --version
autopep8 1.3.5 (pycodestyle: 2.3.1)

C:\>autopep8 test.txt -a -a -a
X = (
    1 +  # 1
    2 +  # 2
    3 +  # 3
    4 +  # 4
    5 +  # 5
    6  # 6 +
    7  # 7
)
```
Note the operator between 6 and 7, which has been moved behind the comment "# 6".

**Comment by hhatto** [comment]
fix in latest master (fffb20b0e5c35a788cad93ae8f2d333f848423ef)

Thanks.
