### ISSUE TITLE
warning diagnostics (eg W503) cannot be fixed in-place

### ISSUE THREAD

**Issue by bje-** [hhatto/autopep8#398]
`flake8` finds warnings like `W503 line break before binary operator`, but `autopep8` will not correct them:

````
$ autopep8 --select=W503 --in-place --recursive .
$ git diff
````
(crickets)

**Comment by hhatto** [comment]
@bje- 
need `-aa` option

**Comment by bje-** [comment]
Nope, that didn't help.

**Comment by hhatto** [comment]
Could you give me some additional information?
* input files or repository url
* Python version
* autopep8 version
* OS environment

**Comment by bje-** [comment]
Unable to reproduce.
