### ISSUE TITLE
autopep8 pending when ignore E303

### ISSUE THREAD

**Issue by willdonggg** [hhatto/autopep8#399]
when use autopep8 format the code below with '--ignore E303', the process will be pending and cpu usage will increase to 100%
```
# define move function
def move_right():
    print('move left')
    return
# define star function

def star():
    print('step1: choose one paper')
    print('step2: xxxx')
    print('step3: xxxx')
    print('step4: xxxx')
    print('step5: xxxx')
    print('step6: xxxx')
    return



# move to right place
move_right()
move_right()

# finish star
star()
star()
```
autopep8 version:  1.3.5
python version：3.6.3
os: CentOS 6.8 or macOS Sierra 10.12.6

**Comment by hhatto** [comment]
fixed in [latest master branch](d6cc49bb6a4afaf67e19a460b6f4b157cd897ea1).

Thanks
