### ISSUE TITLE
E226 missing whitespace around arithmetic operator

### ISSUE THREAD

**Issue by brupelo** [hhatto/autopep8#404]
Hi,

both this snippet:

    c = {}
    d = []
    for a, b in sorted(c.items()):
        d.append("".format(b+','))

and this one:

    c = {}
    d = []
    for a, b in sorted(c.items()):
        d.append("".format(
            b+','
        ))

will report:

    --->  Applying global fix for E265
    --->  0 issue(s) to fix {}

but when doing `flake8 tests.py --ignore=E501,E266,F405,F403,E241` I'll get:

`tests.py:5:10: E226 missing whitespace around arithmetic operator` because `b+','`, any idea how to run autopep to fix errors like this one?

Thanks in advance

**Comment by brupelo** [comment]
It seems the issue is because the default options with `autopep8 1.3.5` are `--ignore errors       do not fix these errors/warnings (default: E226,E24,W503)`

They're different options to the one shown in the [landing page](https://github.com/hhatto/autopep8) btw.

Also, I don't see `E24`  explained anywhere in the docs, how so?

**Comment by hhatto** [comment]
https://github.com/hhatto/autopep8/blob/master/README.rst#id3

update usage sction for default ignore in README.
