### ISSUE TITLE
Does not remove the unneccessary semicolon in the end of the line

### ISSUE THREAD

**Issue by AlexArcPy** [hhatto/autopep8#407]
> >autopep8 --version
> autopep8 1.3.5 (pycodestyle: 2.3.1)

Oddly enough, running `autopep8 --aggressive --aggressive filepath` on a module with the contents:

```
def example2(): return {'has_key() is deprecated':True}.has_key({'f':2}.has_key(''));
```

Produces a line with the semi-colon present in the end of the line.

```
def example2(): return ('' in {'f': 2}) in {'has_key() is deprecated': True};
```

In the main [docs file](https://github.com/hhatto/autopep8#id3) page the semi-colon is gone, but when I run the same contents, it is still present.

Is there a way to remove the such redundant semi-colons?

**Comment by hhatto** [comment]
@AlexArcPy 

fix in [version 1.4](https://pypi.org/project/autopep8/1.4/).
Please version up autopep8.

v1.3.5:
```
$ python autopep8.py --version
autopep8 1.3.5 (pycodestyle: 2.4.0)
$ python autopep8.py -d -aa example.py
--- original/example.py
+++ fixed/example.py
@@ -1 +1 @@
-def example2(): return {'has_key() is deprecated':True}.has_key({'f':2}.has_key(''));
+def example2(): return ('' in {'f': 2}) in {'has_key() is deprecated': True};
```

v1.4:
```
$ python autopep8.py --version
autopep8 1.4 (pycodestyle: 2.4.0)
$ python autopep8.py -d -aa example.py
--- original/example.py
+++ fixed/example.py
@@ -1 +1 @@
-def example2(): return {'has_key() is deprecated':True}.has_key({'f':2}.has_key(''));
+def example2(): return ('' in {'f': 2}) in {'has_key() is deprecated': True}
```

Thanks
