### ISSUE TITLE
don't separate library names in requirements.txt 

### ISSUE THREAD

**Issue by PabTorre** [hhatto/autopep8#408]
When running with double aggressive on requirements.txt
the name of libraries with a hyphen get corrupted with spaces 
which leads to errors when feeding the requirments file to pip. 

Version: 
autopep8 1.3.5 (pycodestyle: 2.3.1)

Expected output: 

should not separate hyphenated library names with spaces. 

Current output: 

hyphenated library names get separated with spaces 

Example: 

make a file requirements.txt with library names containing hyphen 
run autopep8 --aggressive --aggressive 
```
$cat requirements.txt
more-itertools
psycopg2-binary
pytest-cov
python-dateutil
$autopep8 --in-place --aggressive --aggressive requirements.txt
$cat requirements.txt
more - itertools
psycopg2 - binary
pytest - cov
python - dateutil
```

**Comment by hhatto** [comment]
It is pointed out even in pycodestyle.

```
$ cat requirements.txt
more-itertools
$ pycodestyle --select=E,W requirements.txt
requirements.txt:1:5: E226 missing whitespace around arithmetic operator
$ autopep8 -a -a -r -d requirements.txt
--- original/requirements.txt
+++ fixed/requirements.txt
@@ -1 +1 @@
-more-itertools
+more - itertools
```

ignore with `-r` (recursive mode) in this case.

```
$ autopep8 -a -a -r -d .
$
```

Thanks.

**Comment by myint** [comment]
@PabTorre The input to `autopep8` is meant to be Python code. It isn't meant to format generic text files (`requirements.txt`).

**Comment by PabTorre** [comment]
@myint  Should autopep8 ignore no .py files when running recursive?

**Comment by myint** [comment]
It should already ignore non-Python files during recursive mode. See @hhatto's comment above with `.` as the argument.

But if the user explicitly passes in an arbitrary fie as an argument, `autopep8` does what the user asks.
