### ISSUE TITLE
autopep8 cannot fix lines that are too long

### ISSUE THREAD

**Issue by jkeesh** [hhatto/autopep8#42]
is this because there is no way to know where to split this? or you cant do it without modifying the meaning of the code? 

i'm not sure if there is a way to add line continuation characters or to break up chained functions, but this is another issue i saw

**Comment by stefanmohl** [comment]
I have a good use case: Documentation strings. They are a bother to clean up and re-format manually when you change them.

**Comment by myint** [comment]
Hi @stefanmohl, for docstrings, I wrote [docformatter](https://github.com/myint/docformatter). It might be worth a try.

**Comment by stefanmohl** [comment]
Great! Now I have simply pipelined docformatter after autopep8, and my problem is solved! Thanks!
