### ISSUE TITLE
Autopep8 don't fix E225:missing whitespace around operator

### ISSUE THREAD

**Issue by PhungXuanAnh** [hhatto/autopep8#424]
I try autopep8 on vscode and using command line, but it don't fix [pep8] E225:missing whitespace around operator

for example with code
a = b+1

it should change to: a = b + 1

**Comment by hhatto** [comment]
This case is E226.

```
$ cat 225.py
b = 2
a = b+1
$ pycodestyle --select=E,W
225.py:2:6: E226 missing whitespace around arithmetic operator
```

and E226 is in default ignore.
So you can specify it by specifying `--select=E,W` option.
 
```
$ autopep8 -d ~/gox.py --select=E,W
--- original//Users/hattori-h/gox.py
+++ fixed//Users/hattori-h/gox.py
@@ -1,2 +1,2 @@
 b = 2
-a = b+1
+a = b + 1
```
