### ISSUE TITLE
Prefer to get non-zero exit status if diff exists

### ISSUE THREAD

**Issue by sonots** [hhatto/autopep8#432]
`autopep8 --diff` always exits with status code 0 currently. But, I prefer to get non-zero exit status if diff exists. This behavior is useful to use autopep8 in CI.

FYI: [yapf](https://github.com/google/yapf) exits with status code 1 if diff exists.

**Comment by hhatto** [comment]
FYI:

return zero commands

* `black --diff`
* `autoflake`
* `docformatter`
* `gofmt -d`
* `git diff`

return non-zero commands

* `yapf -d`
* `diff`
* `git diff --exit-code`

**Comment by sonots** [comment]
`git diff --exit-code` approach looks nice for me.

**Comment by hhatto** [comment]
It is scheduled to be released in version 1.4.1 or 1.5.
