### ISSUE TITLE
Pycodestyle unused-import

### ISSUE THREAD

**Issue by anselmos** [hhatto/autopep8#436]
I've used autopep8 for project and I'm really happy about how it works.

I'd like to know is there a possibility to add feature of removing any `unused-import` as an parameter-argument like `--remove-unused-imports` ? 

If there is anything I could do to create it, please provide me some feedback.

Thanks!

**Comment by hhatto** [comment]
unused-import is annotation of pyflakes.

use [pyflakes](https://github.com/PyCQA/pyflakes) and [autoflake](https://github.com/myint/autoflake).

Thanks.

**Comment by gotexis** [comment]
Some of the functionalities of flake are not as well designed as autopep8, such as they don't have the native command to run as a python module, nor linting on a string instead of a file.
