### ISSUE TITLE
Multiline if statements that have a . cause a repeat of the rest of the statement in v1.4.1

### ISSUE THREAD

**Issue by ATRAN2** [hhatto/autopep8#440]
autopep8 version:
```
$ autopep8 --version
autopep8 1.4.1 (pycodestyle: 2.4.0)
```
Python version:
```
$ python --version
Python 3.6.0
```
Host info:
```
$ uname -a
Linux xxxx 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Example testcase:
```
if(
    foo.bar and
    baz
):
    print('whomp')

if(
    foo.bar or
    baz
):
    print('whomp')
```

Expected result:
```
if(
    foo.bar and
    baz
):
    print('whomp')

if(
    foo.bar or
    baz
):
    print('whomp')
```
(Essentially a noop)

Actual result:
```
$ autopep8 example.py
if(
    foobar and
    bar and
    . baz
):
    print('whomp')

if(
    foobar or
    bar or
    . baz
):
    print('whomp')
```

1.4.1 should be the most recent version as of this post

Reverting to 1.4 seems to work

**Comment by asottile** [comment]
#441 may be the same thing, though on a whole different level

**Comment by hhatto** [comment]
@ATRAN2 

fix in latest master.

version 1.4.2 just released.
https://pypi.org/project/autopep8/1.4.2/

Could you try once again with version 1.4.2?

Thanks.

**Comment by ATRAN2** [comment]
Updated to 1.4.2 and it works just fine now, thanks!
