### ISSUE TITLE
w503: error indexing an empty string when E721 is ignored

### ISSUE THREAD

**Issue by ideasman42** [hhatto/autopep8#443]
Run the following command with the attached file:
```
autopep8 --ignore E721 mathutils.Quaternion.py
```

[mathutils.Quaternion.py.txt](https://github.com/hhatto/autopep8/files/2500582/mathutils.Quaternion.py.txt)

**Comment by hhatto** [comment]
fix in latest master.

version 1.4.2 just released.
https://pypi.org/project/autopep8/1.4.2/

Thanks.
