### ISSUE TITLE
Q: "Applying global fix for <CODE>" - what does it mean and how to resolve

### ISSUE THREAD

**Issue by tkang007** [hhatto/autopep8#444]
Hello,

I have a question regarding a verbose message: "Applying global fix for <CODE>"
My question is what does the message means, and how to resolve the error.
It was not removed even though I use --in-place option as below multiple time.

autopep8 --verbose --global-config /dev/null --ignore-local-config --max-line-length=160 -aa --recursive --in-place  pkg/mod.py

My environments is Window7, Python 2.7, and autopep8 1.3.5 (pycodestyle: 2.3.1)

Thanks in advance.
Taewon

**Comment by martemyev** [comment]
Hi Taewon,
The message will go away if you don't run autopep8 in the 'verbose' mode, i.e. you need to remove '--verbose' from the command line options.
