### ISSUE TITLE
invalid exit code when '--in-place --exit-code' options are set and no changes was made

### ISSUE THREAD

**Issue by VolodymyrLavrenchuk** [hhatto/autopep8#455]
https://github.com/hhatto/autopep8/pull/437/files#diff-1f8ef9e30f90510a0b8497bc11ffe74fR4137
**ret** variable will contain array of empty strings if fix_multiple_files has not made any changes.
Ex: ['', '', '', '']
But return code will be 2 because of len(['', '', '', '']) > 0

Check could be like: 

`len(''.join(ret)) > 0`

**Comment by hhatto** [comment]
Thaks for your bug reporting.

fix in latest master branch (40bcf6f126f11f6957f7b2c31d880245843b2242)
