### ISSUE TITLE
Problems installing Autopep8 in VS Code

### ISSUE THREAD

**Issue by tomshelley** [hhatto/autopep8#465]
_I see similar issues but unfortunately none of the solutions on here have resolved the issue (I am running VS Code 3.5.2 on Linux Mint 18.3 Sylvia). When trying to install autopep8 I get the following:_

$ /usr/bin/python3 -m pip install -U black --user
Collecting black
  Using cached https://files.pythonhosted.org/packages/e8/5f/0f79fcd943ba465cbd4bf303c9794970c13a95e5456630de9f72e7f37ad4/black-18.9b0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1_c9dsrf/black/
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

_I tried:_ 
pip install --upgrade setuptools

_but got the following_

pip install --upgrade setuptools
/home/tom/.local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Requirement already up-to-date: setuptools in /home/tom/.local/lib/python2.7/site-packages (40.6.3)

_please forgive my ignorance I'm very new to this.

Many thanks_

**Comment by asottile** [comment]
you probably want `apt install python3-setuptools` or to use `python3 -m pip install --user setuptools`

**Comment by tomshelley** [comment]
Thanks for your reply! Both commands went through without problems, but when i try to run the Autopep8 installation again i still get exactly the same error:

Is there anything else I can try?

/usr/bin/python3 -m pip install -U black --user
Collecting black
  Using cached https://files.pythonhosted.org/packages/e8/5f/0f79fcd943ba465cbd4bf303c9794970c13a95e5456630de9f72e7f37ad4/black-18.9b0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6vqaoy91/black/setup.py", line 7, in <module>
        assert sys.version_info >= (3, 6, 0), "black requires Python 3.6+"
    AssertionError: black requires Python 3.6+

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6vqaoy91/black/
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by asottile** [comment]
that's a different error, that's black failing to install because you're running python3.5 probably?

mint is ubuntu based right? you might have some luck with [deadsnakes](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) if you need a newer version of python

**Comment by tomshelley** [comment]
Thanks so much again! I really appreciate it.

Got most of that working, but at the 'make' stage I got this at the end:

checking whether build environment is sane... configure: error: unsafe
srcdir value: '/home/tom/Downloads/python3.6-ubuntu-xenial
(2)/Modules/_ctypes/libffi'
Failed to configure _ctypes module
*** WARNING: renaming "_ctypes" since importing it failed:
build/lib.linux-x86_64-3.6/_ctypes.cpython-36m-x86_64-linux-gnu.so: cannot
open shared object file: No such file or directory
error: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.6/_
ctypes.cpython-36m-x86_64-linux-gnu.so' -> 'build/lib.linux-x86_64-3.6/_
ctypes.cpython-36m-x86_64-linux-gnu_failed.so'
Makefile:603: recipe for target 'sharedmods' failed
make: *** [sharedmods] Error 1

and for 'make test':

make test
 CC='gcc -pthread' LDSHARED='gcc -pthread -shared    ' OPT='-DNDEBUG -g
-fwrapv -O3 -Wall' _TCLTK_INCLUDES='' _TCLTK_LIBS='' ./python -E
./setup.py  build
running build
running build_ext
INFO: Can't locate Tcl/Tk libs and/or headers
warning: building with the bundled copy of libffi is deprecated on this
platform.  It will not be distributed with Python 3.7
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for gsed... sed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... configure: error: unsafe
srcdir value: '/home/tom/Downloads/python3.6-ubuntu-xenial
(2)/Modules/_ctypes/libffi'
Failed to configure _ctypes module
*** WARNING: renaming "_ctypes" since importing it failed:
build/lib.linux-x86_64-3.6/_ctypes.cpython-36m-x86_64-linux-gnu.so: cannot
open shared object file: No such file or directory
error: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.6/_
ctypes.cpython-36m-x86_64-linux-gnu.so' -> 'build/lib.linux-x86_64-3.6/_
ctypes.cpython-36m-x86_64-linux-gnu_failed.so'
Makefile:603: recipe for target 'sharedmods' failed
make: *** [sharedmods] Error 1

Am I missing CGC or something? Not completely sure what that is.....sorry

**Comment by asottile** [comment]
looks like you're building python from source -- you'll need at least `libffi-dev libssl-dev libreadline-dev` (looks like the one it's erroring on is `libffi-dev` specifically)

If you want to just use binary packages you can set up deadsnakes via:

```bash
sudo add-apt-repository ppa:deadsnakes
sudo apt update
sudo apt install python3.6
```

(or something similar)

**Comment by hhatto** [comment]
This issue closes.
Please reopen if a problem occurs.
