### ISSUE TITLE
autopep8 changed my code

### ISSUE THREAD

**Issue by sazad44** [hhatto/autopep8#469]
I ran autopep8 and it changed my code to previous versions apparently. I am using emacs. That is insane!

**Comment by sazad44** [comment]
I tested it and with --in-place and one --aggressive flag it will change type(obj) != class to not isinstance(obj, class). They are not equivalent.

**Comment by Hanaasagi** [comment]
`--aggressive` will make non-whitespace changes. `type(a) != A` is not suggested in [E721](https://lintlyci.github.io/Flake8Rules/rules/E721.html). 

Maybe you can try `--ignore=E721`

**Comment by hhatto** [comment]
@sazad44 
Could you show me specific code?
Also, is the code linted with pycodestyle?
