### ISSUE TITLE
E712 if cond is

### ISSUE THREAD

**Issue by cansarigol** [hhatto/autopep8#472]
E712 comparison to False should be 'if cond is False:' or 'if not cond:'
Can be added?

**Comment by hhatto** [comment]
@cansarigol 
Can you indicate the specific code?
Also, is the code linted with pycodestyle?

**Comment by cansarigol** [comment]
I've dealt a project that contains some code like this 'if x == False:'. When i checked the code with flake8, l  got this E712 error.

**Comment by hhatto** [comment]
Oh, OK.

Currently you need to specify with the `-aaa` option.
We plan to change it to work even without the `-aaa` option.

Thanks.

**Comment by cansarigol** [comment]
By the way, the problem is when I try to fix with `autopep8 --in-place --aggressive`, nothing happens. But except this other problems are fixed.

**Comment by hhatto** [comment]
version info:
```
(py372) hattorihideo@k2-3 ~
> pycodestyle --version
2.5.0
(py372) hattorihideo@k2-3 ~
> autopep8 --version
autopep8 1.4.3 (pycodestyle: 2.5.0)
 ```

target file:
```
(py372) hattorihideo@k2-3 ~
> cat -n aa.py
     1	x = 1
     2	if x == False:
     3	    print(x)
```

execute pycodestyle & autopep8:
```
(py372) hattorihideo@k2-3 ~
> pycodestyle aa.py
aa.py:2:6: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
(py372) hattorihideo@k2-3 ~
> autopep8 -aaa -d aa.py
--- original/aa.py
+++ fixed/aa.py
@@ -1,3 +1,3 @@
 x = 1
-if x == False:
+if not x:
     print(x)
(py372) hattorihideo@k2-3 ~
> autopep8 -aaa -i aa.py
(py372) hattorihideo@k2-3 ~
> pycodestyle aa.py
(py372) hattorihideo@k2-3 ~
> cat -n aa.py
     1	x = 1
     2	if not x:
     3	    print(x)
```

**Comment by cansarigol** [comment]
> Oh, OK.
> 
> Currently you need to specify with the `-aaa` option.
> We plan to change it to work even without the `-aaa` option.
> 
> Thanks.

sorry I missed this message.

**Comment by cansarigol** [comment]
> > Oh, OK.
> > Currently you need to specify with the `-aaa` option.
> > We plan to change it to work even without the `-aaa` option.
> > Thanks.
> 
> sorry I missed this message.
