### ISSUE TITLE
--max-line-length -> error: incorrect number of arguments

### ISSUE THREAD

**Issue by spitfireCH** [hhatto/autopep8#477]
It's probably just me being inexperienced, but I don't manage to set the --max-line-length option. I tried various ways to set it, but always get the error "incorrect number of arguments" or other errors. Ways  I tried:
autopep8 --max-line-length=120
autopep8 --max-line-length 120
autopep8 "--max-line-length 120"
autopep8 [--max-line-length 120]
autopep8 [--max-line-length=120]
autopep8 --in-place --aggressive --aggressive --max-line-length=120
autopep8 --in-place --aggressive --aggressive --max-line-length 120

I am running these commands from the terminal window inside Visual Studio Code. 

What is the proper way to set this option?

Suggestion: maybe include some examples in the usage part of the manual. I am sure that usage is obvious for pros, but not so much for beginners like me :)

Thanks!

**Comment by hhatto** [comment]
@spitfireCH 
Have you specified the target files for autopep8?

for example:
```
$ autopep8 --max-line-length=120 TARGET.py
```

Thanks

**Comment by spitfireCH** [comment]
Hi hhatto
thanks for your help! Apparently, I misunderstood the idea of this command. I thought I could change the option in Visual Studio Code that way, which uses autopep8 to format the code. 

Your example works, but doesn't quite do what I was hoping for. Is there a way to change max-line-length as default option to be used by Visual Studio Code? 

Thanks and best regards

**Comment by hhatto** [comment]
I am not a VSCode expert, so it may be wrong, but it may not be like the following?

<img width="1545" alt="vscode_autopep8_args" src="https://user-images.githubusercontent.com/150309/55422359-6fd2b700-55b6-11e9-8ad5-e9474f733bb7.png">

add this line in USER SETTINGS
```
"python.formatting.autopep8Args": ["--max-line-length=XX", ]
```

Thanks

**Comment by spitfireCH** [comment]
Thank you, I will try that!

**Comment by nathanchere** [comment]
You can also solve this without requiring editor-specific settings by adding a `.pep8` file to the root of your project with the following:

```
[pycodestyle]
max_line_length = 120
```
