### ISSUE TITLE
IGNORE whitespace errors? Which rule to apply?

### ISSUE THREAD

**Issue by gotexis** [hhatto/autopep8#479]
Hey I would like to format my code like this
```python

    id                = LALALA
    domain_id         = asfddsaf
    name                 = FooBar
```

(the equals are kind of trimmed, but not correctly displaying here due to font not being monospaced.)

Too bad I cannot find which rule to use, to ignore whitespace squashing.

**Comment by gotexis** [comment]
After looking at the source code of this project, I believe e224 fixes multiple whitespaces around operator.

I will try to ignore it for now but not sure if it will break some other desirable checks.

**Comment by gotexis** [comment]
In readme it suggested E211, which is not correct -- the correct rule to ignore is E221.

I hope the document got fixed :)

**Comment by hhatto** [comment]
see http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
