### ISSUE TITLE
Parallel jobs not supported with --diff

### ISSUE THREAD

**Issue by ulope** [hhatto/autopep8#480]
Currently autopep8 aborts with the error message `parallel jobs requires --in-place` when trying to run with `--jobs 0 --diff`.

Is there a reason why this shouldn't be allowed?

**Comment by myint** [comment]
Multiple jobs all writing to the same standard out stream will result in corrupted output.

**Comment by ulope** [comment]
Shouldn't be too much work to pipe the output back to the parent process and have it print it in a consistent way.

I'll see if I have time for a PR in the next few days.

**Comment by hhatto** [comment]
This feature was included in the latest master branch.
It will be included in version 1.5.2, which will be released next week.

Thanks
