### ISSUE TITLE
from __future__ import annotations moved incorrectly

### ISSUE THREAD

**Issue by ikamensh** [hhatto/autopep8#481]
I have used the command from the readme (autopep8 --aggressive -aggressive) and as a result my code stoped running:
SyntaxError: from __future__ imports must occur at the beginning of the file

The reason is that the from __future__ imports were moved to seemingly random location among other imports.

**Comment by hhatto** [comment]
@ikamensh 
Thanks for reporting.

Could you please provide a minimal script that reproduces your issue?
And please provide more information.

* autopep8 version
* Pyhton version
* OS (Linux, Windows, macOS, etc...)

**Comment by ikamensh** [comment]
it was the pip install version at the time of reporting (29.03.2019) on macOS Mojave. 
I have run it on the code of my game project (https://github.com/ikamensh/pydolons) and this occured in multiple files.
Python where autopep8 is installed: 3.6 (the project uses 3.7 actually)

**Comment by hhatto** [comment]
Specifically, which file causes an error? Although I ran with autopep8 version 1.4.3 (Python3.7.3), I was not able to confirm a particularly problematic operation.

```
> git log --oneline -n1
5dcce80 (HEAD -> develop, origin/develop, origin/HEAD) add walls for DreamGame
> autopep8 --version
autopep8 1.4.3 (pycodestyle: 2.4.0)
> autopep8 -aa --in-place -r .
> git diff
```

diff is in the link below:
https://gist.github.com/hhatto/89bc96f6524309586e2c151b39391557
