### ISSUE TITLE
Breaks program functionality even without --aggressive

### ISSUE THREAD

**Issue by sguillia** [hhatto/autopep8#495]
---
## Python Code

main.py
```python
import os
os.environ['abort'] = "no"
import foo
```

foo.py
```python
import os

if os.environ['abort'] != 'no':
	raise Exception
```

## Steps to reproduce problem

1. Watch as the program runs normally
```
$ python3 main.py
```

2. Run autopep8
```
$ autopep8 --in-place main.py
```

3. Watch as the program functionality / meaning has changed
```shell
$ python3 main.py
Traceback (most recent call last):
...
KeyError: 'abort'
```

4. Look at what autopep8 did to main.py:
```python
import foo
import os
os.environ['abort'] = "no"
```

Some packages like tensorflow require environment variables to be set before importing them. I agree this is bad practice, nonetheless I believe autopep8 should not break the program functionality without the `--aggressive` flag. This applies for all fixes, not only the `E402` which is causing trouble here.

## Command Line and Configuration
No config file

## Your Environment
* Python version: Python 3.5.2
* autopep8 version: autopep8 1.4.4 (pycodestyle: 2.5.0)
* Platform: Linux Ubuntu amd64

**Comment by hhatto** [comment]
use `NOQA`

main.py
```
import os
os.environ['abort'] = "no"
import foo  # NOQA
```
