### ISSUE TITLE
unknown option 'indent-size' ignored

### ISSUE THREAD

**Issue by MarkGreeny** [hhatto/autopep8#499]
My autopep8 does not seem to recognize the `indent-size` option. I am prompted with

> unknown option 'indent-size' ignored

I installed the autopep8 using pip3. I attach the config bellow. Please inform me what i am doing wrong.

### Config

```
[pycodestyle]
indent-size=2
ignore = E111,E114
```
(note that i get the sam ebehaviour if i use a [pep8] block)

### Command Line
```shell
$ autopep8 --global-config /path/to/config file.py
```

## Your Environment
* Python version: 3.7.3
* autopep8 version: autopep8 1.4.4 (pycodestyle: 2.4.0)
* Platform: linux

**Comment by Hanaasagi** [comment]
If you mean autopep8 could not change the indent as you wish. I could not reproduce this problem.

A simple test in clean environment with docker.

```Bash
#!/bin/bash

cat > ./t.sh <<EOM
#!/bin/bash

pip install pycodestyle==2.4.0 autopep8==1.4.4
cat > /root/test.py <<EOF
def test():
    pass
EOF

cat > /root/expect.py <<EOF
def test():
  pass
EOF

cat > /root/.pep8 <<EOF
[pycodestyle]
indent-size=2
ignore = E111,E114
EOF

autopep8 --version
autopep8 --in-place --global-config /root/.pep8 /root/test.py
echo 'diff here'
diff /root/expect.py /root/test.py
EOM

docker run --rm -v $PWD/t.sh:/root/t.sh python:3.7.3 bash /root/t.sh
```

There is no diff. autopep8 changed the indent from 4 to 2. Please provide more information.

**Comment by MarkGreeny** [comment]
@Hanaasagi thank you for reply.

Running version outputs
```
autopep8 --version
```
> autopep8 1.4.4 (pycodestyle: 2.4.0)

**Input file**
```python
def foo():
  return 1
```

Running the command

```
autopep8 input.py > result.py
```

Produces the file
```python
  unknown option 'indent-size' ignored
  unknown option 'indent-size' ignored
def foo():
  return 1
```

Note that the config is still
```
[pycodestyle]
indent-size=2
ignore = E111,E114
```

**Comment by MarkGreeny** [comment]
### Update
 If i remove `indent-size` from the config
```
[pycodestyle]
ignore = E111,E114
```
and give `indent-size=2` as an extra argument of the command
``` 
autopep8 --indent-size=2 input.py > result.py
```

Eveything works as expected.

So, it seems that it is unable to read this from the config, but is perfectly happy to do so from the command line argument.

**Comment by Hanaasagi** [comment]
The warning message `unknown option ...` is from pycodestyle 

Check this https://github.com/PyCQA/pycodestyle/blob/f73c4bb211986cd8d340de2f018c3ff6a3d73c5f/pycodestyle.py#L2435

And the`indent-size` is not listed in  support config. 
Check this https://github.com/PyCQA/pycodestyle/blob/f73c4bb211986cd8d340de2f018c3ff6a3d73c5f/pycodestyle.py#L2325

Please use the `--indent-size` in  command line. Thanks

**Comment by MarkGreeny** [comment]
@Hanaasagi Thank you for your continued help. Taking your input into action, I see one can do:

```
[pycodestyle]
ignore = E111,E114
[pep8]
indent-size=2
```
which behaves as expexted.
