### ISSUE TITLE
autopep8 not respecting --global-config when doing an --in-place directly on file

### ISSUE THREAD

**Issue by thernstig** [hhatto/autopep8#501]
When using the autopep8 command with a `--global-config` the global config is not respected when doing an `--in-place` directly on a file. This is especially problematic with editors such as VS Code as there is no way to respect the .flake8 file contained in the root of the repo. See https://github.com/microsoft/vscode-python/issues/7040

## Command Line and Configuration
`.flake8`

```ini
[flake8]

exclude=
  pathto/file.py
```

Command Line
```shell
$ autopep8 --global-config /home/username/project/.flake8 -r -i pathto/ # Respects the ignore
$ autopep8 --global-config /home/username/project/.flake8 -i pathto/file.py # Does NOT respect the ignore
```

## Your Environment
* Python version: 3.6.9
* autopep8 version: 1.4.4 (pycodestyle: 2.5.0)
* Platform: Linux

**Comment by thernstig** [comment]
I want to note that this makes the VS Code Python extension completely useless in regards to respecting autopep8 configuration options, as per https://github.com/microsoft/vscode-python/issues/7040. They claim the fix needs to be done here in autopep8.

**Comment by hhatto** [comment]
Thanks for reporting.
It will be included in version 1.5.2, which will be released next week.

**Comment by thernstig** [comment]
@hhatto This has not been properly fixed unfortunately. I tested two things.

These now properly respect the `.flake8` and the `exclude=` directive:
```sh
~/code/.venv/bin/python -m autopep8 --global-config .flake8 --diff path/to/file.py
~/code/.venv/bin/python -m autopep8 --global-config .flake8 --in-place path/to/file.py
```

These do not:
```sh
 ~/code/.venv/bin/python -m autopep8 --global-config .flake8 --diff ~/code/path/to/file.py
 ~/code/.venv/bin/python -m autopep8 --global-config .flake8 --in-place ~/code/path/to/file.py
```

Unfortunately, VS Code uses the **absolute path** approach, and the fix done does not work with that. I confirmed that the fix works with relative paths though.

**Comment by hhatto** [comment]
@thernstig 
autopep8 is using [fnmatch module](https://docs.python.org/3.7/library/fnmatch.html).
If your example looks like this, the workaround is to write in `.flake8`

```
[flake8]
exclude = */path/to/file.py
```

**Comment by thernstig** [comment]
@hhatto That is unfortunately not a proper fix. Using `*/path/to/file.py` will invert the behavior.

Now this works:

```sh
~/code/.venv/bin/python -m autopep8 --global-config .flake8 --diff ~/code/path/to/file.py
```

but not

```sh
~/code/.venv/bin/python -m autopep8 --global-config .flake8 --diff path/to/file.py
```

Also, [the documentation](https://flake8.pycqa.org/en/latest/user/configuration.html) does not show anything about `*/` (but I assume that is irrelevant, because the workaround does not work).

There needs to be a consistent way to add `exclude` like this:

```
exclude =
  path/to/file.py
```

that works in both absolute and non-absolute calls to the file  via CLI. If this is not fixed that autopep8 basically does not work depending on the editor one uses.
