### ISSUE TITLE
Exclude-Section

### ISSUE THREAD

**Issue by qohelet** [hhatto/autopep8#516]
---

## Python Code
```python

import django
django.setup()
from .forms import *
```
I want to be able a certain section of my code to be excluded from the reformatting of autopep8.
In some of my tests I have to avoid the error:` django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`
 with this imports:
```python
import django
django.setup()
from .forms import *
```
In this specific order. But this order is always reversed to:
```python
from .forms import *
import django
django.setup()
```
And my code fails. Please give me the freedom to avoid some of my code from being formatted. 
Usually I'm satisfied with E402. Just in this case it's making my code fail

## Your Environment
* Python version: 3.6.8
* autopep8 version: 1.4.4
* emacs version: 26.3
* Platform: Ubuntu 18.04

**Comment by hhatto** [comment]
should use `NOQA` comment.

example: 
```python
import django
django.setup()
from .forms import *  # NOQA
```

Thanks

**Comment by qohelet** [comment]
Perfect, didn't know about that. 
Thank you!
