### ISSUE TITLE
No difference detected between " e "and " é " (french accents) in DataGrip

### ISSUE THREAD

**Issue by Doria2020** [hhatto/autopep8#522]
Hello, I created tables with DataGrip (MySQL) and as the words in the tables are french I used " collate = utf8_unicode_ci ". The words and the accents are correctly displayed but the program doesn't make the difference between " e " and " é ". And as I have to detect duplicates, this is an important problem.

For example, when I use this statement : 

SELECT word FROM table_2 WHERE word = 'bouché' ;

The result I get is this one : 

![Picture1](https://user-images.githubusercontent.com/60873772/74135798-3d89e100-4bed-11ea-8371-253b4f32ec1f.png)

Both words are in my table, but they are not written the same way and have different meanings. 
I already checked in the settings if the encoding was utf-8 and it is (as the accents are correctly displayed). 
How can fix this problem and make sure that "bouche" and "bouché" (for example) are not considered as identical ? 

Thank you in advance for your help !

**Comment by hhatto** [comment]
Is this a problem with autopep8?

For autopep8 problems, please specify the target Python source code and command execution examples.

Thanks

**Comment by Doria2020** [comment]
No I don't think so. I didn't use autopep8, the problem I have is only related to MySQL databases.
