### ISSUE TITLE
autopep 8 incorrectly change the order of import statements

### ISSUE THREAD

**Issue by qiulang** [hhatto/autopep8#523]
---
I initially thought it was a vscode bug so I opened an issue for them,  check here https://github.com/microsoft/vscode-python/issues/10069 

## Python Code
Put test code & source code at the same level as pytest document suggested 

```
mypkg/
    __init__.py
    app.py
    view.py
tests/
    test_app.py
    test_view.py

```

So in the test code the first line is alway

```
import sys
sys.path.append("../")
# then import my app code
```

Then autopep8 will change it to 

```
import my app code
import sys
sys.path.append("../")
```

Then I would get ModuleNotFoundError: No module named xxx

## Your Environment
* Python version: 3.7.3
* autopep8 version: 1.5
* Platform:  macOSX

**Comment by hhatto** [comment]
use `NOQA` with comment line.

see also: https://github.com/hhatto/autopep8/issues/516#issuecomment-575099796

Thanks

**Comment by mh-firouzjaah** [comment]
ok bro nut were is the correct answer for the problem???

**Comment by VietTralala** [comment]
>



> ok bro nut were is the correct answer for the problem???

For every import line after  `sys.path.append('..')` you just put the comment  `#NOQA' at the end.
So the code will look as follows:
```
import sys
sys.path.append("../")
import my app code #NOQA
```

**Comment by mh-firouzjah** [comment]
Thank you.
