### ISSUE TITLE
Expected pyproject.toml configuration syntax incompatible with TOML format

### ISSUE THREAD

**Issue by OliverSieweke** [hhatto/autopep8#528]
#510 introduced a configuration option through the `pyproject.toml` file, under a `[tool.autopep8]` header. However the expected syntax conforms to the [syntax of the `setup.cfg` file](https://docs.python.org/3/distutils/configfile.html), which is not quite compatible with the [TOML](https://github.com/toml-lang/toml) format.

The following example from the documentation works fine on its own:

```ini
[tool.autopep8]
max_line_length = 120
ignore = E501
```

However this syntax will break other tools that use the `pyproject.toml` file, for instance leading them to interpret `E203` as a float without a leading digit in this case. I believe the correct syntax should be: 

```toml
[tool.autopep8]
max_line_length = 120
ignore = ['E501']
```

The current parser will not pick up this corrected syntax however. This makes it impossible to use the `pyproject.toml` configuration option, while also using other tools that expect a strict [TOML](https://github.com/toml-lang/toml) format.

I believe this is the relevant part of the code:
https://github.com/hhatto/autopep8/blob/3d5506e612f7f86bd9a516cc8d0c7642b81efa94/autopep8.py#L3821-L3862

---

Quite new to Python, but happy to give this a shot...

---

## Your Environment
* Python version: `3.7`
* autopep8 version: `1.5`
* Platform: macOSX

**Comment by bjrne** [comment]
I ran into the same problem and can confirm it. Thus, TOML support is currently unusable for me :frowning_face:

**Comment by pitrou** [comment]
I also tried the following `pyproject.toml` snippet and it seems completely ignored by `autopep8`:
```toml
[tool.autopep8]
ignore = "E211,E225,E226,E227,E401,E402,W504"
filename = "*.py,*.pyx,*.pxd,*.pxi"
```

If `autopep8` doesn't recognize that syntax, I would at least expect an error to be written out instead of silently ignoring it...

**Comment by hhatto** [comment]
fix in latest master.

Could you try once again with master branch:
```
$ pip install --upgrade git+https://github.com/hhatto/autopep8
```

We plan to release it in version 1.5.3.

Thanks.

**Comment by OliverSieweke** [comment]
Brilliant, thanks @hhatto ! Sorry I missed your request for testing. But it all seems to be working fine so far.
