### ISSUE TITLE
when __all__ var is defined over multiple lines, import annotations moved incorrectly

### ISSUE THREAD

**Issue by parthlathiya** [hhatto/autopep8#529]
---

## Python Code
```python
__all__ = [
	'temp1',
	'temp2'
]

temp1 = 1
temp2 = 2

import time 

print(time.time())
```

## Command Line and Configuration
`.pep8`, `setup.cfg`, ...

```ini
[pep8]

```

Command Line
```shell
$ autopep8 
```

## Your Environment
* Python version: 2.7.16
* autopep8 version: 1.5 (pycodestyle: 2.5.0)
* Platform: macOSX

## autopep8 output
```python
__all__ = [
    import time
    'temp1',
    'temp2'
]

temp1 = 1
temp2 = 2


print(time.time())
```

**Comment by hhatto** [comment]
Thanks for reporting.

fix in 3a89645ae44375d080110f2ebac0c77501a8af1e.

We will be releasing version 1.5.1 with this fix this week.
