### ISSUE TITLE
:= formatted wrongly

### ISSUE THREAD

**Issue by BornForFever** [hhatto/autopep8#531]
In Python 3.8, the walrus operator `:=` means assigning a value to a variable in an expression, e.g.
```python

if (n := len(a)) > 10:  # avoid calling len() twice
    print(f"List is too long ({n} elements, expected <= 10)")
```
For a full description, see [PEP 572](https://www.python.org/dev/peps/pep-0572).
However, when I try to format `a := b` using autopep8, it will turn to `a: = b` by mistake. I hope this bug will be solved. Thanks!

---

## Python Code
```python

if (key := keycode[1]) == 'n': do_something()
```

## Command Line and Configuration
`.pep8`, `setup.cfg`, ...

```ini
[pep8]
# default
```

Command Line
```shell
python -m autopep8 uieditor/uieditor.py
```

## Your Environment
* Python version: 3.8.2
* autopep8 version: 1.5
* Platform: windows

**Comment by hhatto** [comment]
Duplicated #507 

https://github.com/hhatto/autopep8/issues/507#issuecomment-549142358
