### ISSUE TITLE
Bug in Logical statement 

### ISSUE THREAD

**Issue by mradultiw** [hhatto/autopep8#555]
## Logical bug found

I've a package on PyPi ([pyropes.PyPI](https://pypi.org/project/pyropes/)) which I want to refactor according to PEP8 but found this logical statement bug while retesting.

Look at the image attached:

![autopep8 bug](https://user-images.githubusercontent.com/53928253/86531046-a5fa9700-bedb-11ea-8ab4-ac54c7bac528.png)

 This is a serious bug and causes several test fail which earlier were passing.

**Comment by hhatto** [comment]
use `noqa` comment.

example:
```
root = False
if root == False:   # noqa
    print(root)
```

Thanks

**Comment by mradultiw** [comment]
> use `noqa` comment.
> 
> example:
> 
> ```
> root = False
> if root == False:   # noqa
>     print(root)
> ```
> 
> Thanks

Ohh..thanks , I got something new :)
