### ISSUE TITLE
SyntaxWarning when parsing comment

### ISSUE THREAD

**Issue by avancil** [hhatto/autopep8#564]
When running autopep8 against one of my files, it spit out a couple syntax warnings. These appear to result from one line in the file, which is actually just a comment. I can reproduce the issue with just that line in the file.

---

## Python Code
```python
#                        [something] (something)
```

## Command Line and Configuration
Command Line
```shell
$ autopep8 temp.py
<string>:1: SyntaxWarning: 'list' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'list' object is not callable; perhaps you missed a comma?
#                        [something] (something)
$
```

## Your Environment
* Python version: 3.8.5 (pyenv)
* autopep8 version: autopep8 1.5.3 (pycodestyle: 2.6.0)
* Platform: Linux Ubuntu 20.04 LTS
Linux ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hhatto** [comment]
This warning is not necessary and has been fixed so that the warning does not occur.

This change will be released in version 1.5.4.

Thanks 👍
