### ISSUE TITLE
Doesn't set the exit code correctly on permission denied failure

### ISSUE THREAD

**Issue by rwmjones** [hhatto/autopep8#591]
```
$ ll python/guestfs.py 
-r--r--r--. 1 rjones rjones 425068 Mar 22 12:56 python/guestfs.py
$ autopep8-3 -i python/guestfs.py 
[Errno 13] Permission denied: 'python/guestfs.py'
$ echo $?
0
```

Even with the `--exit-code` option it makes no difference.  Note that the input file does need reformatting.

## Your Environment
* Python version: python3-3.9.0-1.fc34.x86_64
* autopep8 version: python3-autopep8-1.5.4-2.fc34.noarch
* Platform: Linux

**Comment by hhatto** [comment]
@rwmjones 
Thanks for reporting.
fix in #592. This fix will be released in version 1.5.7.
