### ISSUE TITLE
New Feature - Constants Automatic Uppercase

### ISSUE THREAD

**Issue by afeser** [hhatto/autopep8#605]
Hi! Firstly I'd like to thank to the developers for this useful repository.

I want to implement a feature for automatically converting global constants to upper case. 

An example would be:
```python
car_min_speed = 10
car_max_speed = 100

class Car:
    def get_avg_speed(self):
        return (car_min_speed + car_max_speed) / 2
```
to be converted to:
```python
CAR_MIN_SPEED = 10
CAR_MAX_SPEED = 100

class Car:
    def get_avg_speed(self):
        return (CAR_MIN_SPEED + CAR_MAX_SPEED) / 2
```

I don't see such feature, and before implementing it, I wanted to ask if this is a useful feature and could be present in the repository; also, to make sure there is no similar development ongoing.

**Comment by hhatto** [comment]
@afeser 

That lint message is supported by pylint (messge is level:`C`, tag:`invalid-name`).
So how about suggesting it to [autopylint](https://github.com/hughdbrown/autopylint)?
For now, there is no plan to support it in autopep8 since it is not supported by pycodestyle either.
