### ISSUE TITLE
Imports moved above a sys.path.insert call, breaking code

### ISSUE THREAD

**Issue by Marsfan** [hhatto/autopep8#613]
Sometimes I need to add a path to the system path to be able to import a file.  (Commonly when working with Sphinx). 

When I then run autopep8 to format the file, it moves the imports to be above the call to `sys.path.insert`, breaking the code. 

---

## Python Code
```python

import os
import sys

sys.path.insert(0, os.path.abspath(".."))
import test_package
```

## Command Line and Configuration
Command Line
```shell
$ autopep8 conf.py
```

## Your Environment
* Python version: 3.9, 3.10
* autopep8 version: 1.5.7
* Platform: Windows 10

**Comment by Marsfan** [comment]
Ok. I just realized that this is likely due to autopep8, not this extension. Closing

**Comment by siddhpant** [comment]
wdym? This is a regression.

**Comment by JakobLeistner** [comment]
Here is a good explanation how to configure the autopep8 extension to not rearrange your imports:
[Allow statements before imports with Visual Studio Code and autopep8 - Stackoverflow](https://stackoverflow.com/questions/54030320/allow-statements-before-imports-with-visual-studio-code-and-autopep8)
