### ISSUE TITLE
`autopep8` over Language Server Protocol and VS Code extension

### ISSUE THREAD

**Issue by karthiknadig** [hhatto/autopep8#624]
The [Python team for VS Code](https://github.com/microsoft/vscode-python) has been working on putting various tools we support behind [LSP](https://microsoft.github.io/language-server-protocol/) and breaking them out into their own extensions This work is now far enough along that we wanted to share the extension prototypes for your tool with you and see if you had any interest in owning the extension or the Python-based LSP server backing it yourself?

If you don't want to take on that reponsibility that's totally fine and understandable! If you want to leave the extension to us we would then publish the extension on the [VS Code Marketplace](https://marketplace.visualstudio.com/VSCode) ourselves. We also plan to publish the extension as open source and support the extension for as long as we felt it made sense to based on usage numbers. But due to the difficulty of migrating extension ownership, we wanted to ask early whether you wanted to own the extension from the start? If you did want to own the extension we would give you the code, help you publish to the VS Code Marketplace, and do anything else we can to help you be successful with this.

We have attached a zip file to this issue containing a prototype extension to give you an idea of what we are planning. You can download it, extract the `.vsix` file, and then [install the VSIX](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix) to try it out [python-autopep8.zip](https://github.com/hhatto/autopep8/files/8073965/python-autopep8.zip). This prototype version was built with python 3.10 and bundles `autopep8` v1.6.0 (as fallback if nothing is found in your environment).

To be very clear, there's no pressure or expectations from us. We just want to make sure you as a project had an opportunity to own this extension instead of us from the get-go before the extension gained traction.

**Comment by karthiknadig** [comment]
For testing this you can follow these steps, after installing. Suppose you have code like this:
```python
import unittest
class TestSum2(unittest.TestCase):
    def test_sum2(self):
        self.assertEqual(sum([1, 2, 3]), 6, "Should be 6")

    def test_sum2_tuple(self):
        self.assertEqual(sum((1, 2, 2)), 6, "Should be 6")
if __name__ == "__main__":
    unittest.main()
```
Right click in the document and select "Format Document With ...":
![image](https://user-images.githubusercontent.com/3840081/153997453-0bd56459-3744-4ccd-a1e0-dad02a619aac.png)
 
You should see two formatters, Select "autopep8":
![image](https://user-images.githubusercontent.com/3840081/154133060-7b2743d1-4ced-42ff-93dc-0694fb30f268.png)


That is, it!

If you want this to happen automatically, set Autopep8 as the default formatter, and enable format on save. Then on save the content will be formatted.

**Comment by hhatto** [comment]
Thanks for opening the issue.

In this repository, we want to provide autopep8 itself as a tool, so we don't plan to own LSP and VS Code extension.
Feel free to implement it 👍

**Comment by karthiknadig** [comment]
This is now available to download https://marketplace.visualstudio.com/items?itemName=ms-python.autopep8

**Comment by agherasim** [comment]
@karthiknadig, having reproduced this issue in one particular file, I was able to eliminate the problem by renaming the file, `main_test.py` -> `main2_test.py`. Renaming the file back causes the issue to reappear. It looks like some sort of cache? could be involved. Any ideas?

**Comment by karthiknadig** [comment]
Are you using the Autopep8 extension if so, could you open a bug there with logs from Output > autopep8
