### ISSUE TITLE
Skip formatting block's on top import don't work for distributed imports

### ISSUE THREAD

**Issue by ridilculous** [hhatto/autopep8#628]
## Python Code
Having

```python
# fmt: off
from os import chdir
# fmt: on

test = False

import configargparse
```

or

```python
# fmt: off
from os import chdir
# fmt: on

def test():
    pass

import configargparse
```

or

```python
# fmt: off
import os
# fmt: on

test = False

import configargparse
```

or similar, formatting moves imports which are spread over the code into the region where formatting is disabled.

```python
# fmt: off
import os; os.cpu_count()
# fmt: on

import configargparse

test = False
def test():
    pass
```

works find though and doesn't move `import configargparse` into the block which is disabled for formatting.

## Expectation
I am looking for a way to pin one specific import to the top of the source without having to rename it and was hoping that, altough the imports are grouped at the beginning of the file, the region with the disabled formatting would be preserved and all other imports grouped below it.

In my specific case, the import will look like

```python
# fmt: off
import os; some_function_invocation_here()
# fmt: on
```

## Environment
* Python version: 3.9.6
* autopep8 version: 1.6.0 (pycodestyle: 2.8.0)
* Platform: windows

**Comment by hhatto** [comment]
Thanks for suggestion.

> works find though and doesn't move import configargparse into the block which is disabled for formatting.

First, the E401 error does not exist, so this behavior is correct.

```console
$ cat valid_one.py
# fmt: off
import os; os.cpu_count()
# fmt: on

import configargparse

test = False
def test():
    pass

$ pycodestyle valid_one.py
valid_one.py:2:10: E702 multiple statements on one line (semicolon)
valid_one.py:8:1: E302 expected 2 blank lines, found 0

$ autopep8 --version
autopep8 1.6.0 (pycodestyle: 2.8.0)
```

> I am looking for a way to pin one specific import to the top of the source without having to rename it and was hoping that, altough the imports are grouped at the beginning of the file, the region with the disabled formatting would be preserved and all other imports grouped below it.

At this time, we have no idea to support this behavior.
