### ISSUE TITLE
Question: How to automatically make spaces between math expressions?

### ISSUE THREAD

**Issue by SUPERustam** [hhatto/autopep8#634]
For instance, I have this code
```python
a=2*5+10/4
```

And I want this as result of autopep8 work: 
```python
a = 2 * 5 + 10 / 4 
```

But I get only this:
```python 
a = 2*5+10/4 
```

What settings I should turn on to let autopep8 do what I want?

## My Environment
* Python version: 3.10.4
* autopep8 version: 1.6.0
* Platform: Linux Manjaro (Arch based)

**Comment by downeykking** [comment]
in the default args setting, --ignore will ignore E226,E24,W50,W690( see https://github.com/hhatto/autopep8/blob/master/README.rst#id3), so you just need to overwrite it.
for instance: `--ignore=`
or `--select=E,W` in this way all E/W problems will be formattd.(see this https://github.com/hhatto/autopep8/issues/424)

**Comment by SUPERustam** [comment]
Thanks!
