### ISSUE TITLE
Infinite loop in autopep8.fix_code()

### ISSUE THREAD

**Issue by Ultimanecat** [hhatto/autopep8#676]
---
Running the following script results in an infinite loop, as fix_lines() will add more and more spaces each iteration between "hits".

## Python Code
```python

import autopep8
txt = '''
class Buggy:
    def _buggy(self):
        for track in filter(lambda x: x._num_losses > self._tolerance
                            or (x._hit_consecutive_frames < self._min_hits and x._num_losses == self._min_hits-1),
                            self._tracker_list_current):
            pass'''
docstring = autopep8.fix_code(txt, {'ignore': ['W292', 'W291']})
```

## Command Line and Configuration
`.pep8`, `setup.cfg`, ...

```ini
[pep8]

```

Command Line
```shell
$ autopep8 
```

## Your Environment
* Python version: python3.10 and python3.8 both reproducible
* autopep8 version: autopep8 1.4.4 (pycodestyle: 2.8.0)、autopep8 1.6.0 (pycodestyle: 2.10.0) 、autopep8 2.0.1 (pycodestyle: 2.10.0) all reproducible
* Platform: windows

**Comment by hhatto** [comment]
@Ultimanecat 

Thanks for reporting.

This problem has been fixed in v2.0.2.
We hope you will try the latest version.
