### ISSUE TITLE
The indent color if the number of spaces is not a multiple of "tabSize"

### ISSUE THREAD

**Issue by Cazs03** [hhatto/autopep8#684]
---

## Python Code
```3.6

```
The indent color if the number of spaces is not a multiple of "tabSize"
image
Issue relate with another extension indent-rainbow
the last part are space not multiple of tab
![image](https://github.com/hhatto/autopep8/assets/6555389/88573179-9799-4f28-9a7d-48915a8ebab3)

## Command Line and Configuration
NONE

```ini
NONE

```

Command Line
```shell
NONE
```

## Your Environment
* Python version: 3.6
* autopep8 version: v2023.4.0
* Platform: windows,

**Comment by hhatto** [comment]
Is this issue for autopep8?
It looks like it is not to me, so I am closing it.
