### ISSUE TITLE
Using "--ignore=E302" and "--ignore=E305" at the same time

### ISSUE THREAD

**Issue by ppzoglou** [hhatto/autopep8#695]
I initially opened an [issue](https://github.com/microsoft/vscode-autopep8/issues/135) on vscode's autopep8 extension repo but as I understand it, there is not much they can do about it so I came here. My desired outcome is for there not to be any extra (more than one) blank lines between defs, classes and the rest of the code, neither above nor bellow them. It seems like I can only achieve one of the two at any time based on what I choose to ignore last.

![example](https://github.com/hhatto/autopep8/assets/93496909/40c14bb2-5e82-4382-ab9a-da2008254d1e)

As you can see in this image, at first there are no extra blank lines. Then I format the file using ignore=E305 last resulting in there only being one extra blank line added between the function and the first print statement. After that I format it again this time with ignore=E302 being the last arg and as you can see its the exact opposite result this time, with the extra blank line being added under the function.

## Environment
* Python version: 3.10.12
* autopep8 version: 2.0.2
* Platform: Ubuntu 22.04.2 LTS

**Comment by hhatto** [comment]
@ppzoglou
If you want to specify more than one, separate them by commas.
For example: `--ignore=E121,E302,E305`
