### ISSUE TITLE
How to stop <- from becomming < -

### ISSUE THREAD

**Issue by RohanVashisht1234** [hhatto/autopep8#746]
---

## Python like Code
```python
<-
```
## After formatting
```python
< -
```

Command Line
```console
$ autopep8 -i ./a.py
```

## My Environment
* Python version: 3.11.x
* autopep8 version: latest
* Platform: all

is there a possible way to restrict `<-` becomming `< -`

**Comment by RohanVashisht1234** [comment]
Basically, I just need some configuration that would restrict `<-` from becomming `< -` after formatting using the command line utility itself.

**Comment by hhatto** [comment]
It does not reproduce in my environment.

```
$ python -V
Python 3.11.7

$ autopep8 --version
autopep8 2.1.1 (pycodestyle: 2.11.1)

$ cat target.py
<-

$ autopep8 -d ./target.py  # Nothing is outputting any differences.
$ autopep8 -aaa -d ./target.py  # Nothing is outputting any differences.
```

**Comment by RohanVashisht1234** [comment]
Sorry, please try this:
```python
def main():
  do IO:
    * <- print("Hello, World!")
    return IO/Done((0))
```

ik, it isn't python code, but try this

**Comment by hhatto** [comment]
> ik, it isn't python code, but try this

autopep8 does not support non-Python code. (Probably pycodestyle is not supported either.)
