### ISSUE TITLE
Splitting long f strings containing hash sign (#) into multiple lines breaks code syntax

### ISSUE THREAD

**Issue by pkv2a** [hhatto/autopep8#753]
---

## Python Code
foo.py:
```python
def foo:
    logger.info(f"some string padding some string padding some string padd {somedict['key1']}, more padding more paddin #: {somedict['dictkey2']}")

```

## Command Line and Configuration
Not using any config files.

Command Line
```console
$ ~/.local/bin/autopep8 foo.py 
def foo:
    logger.info(f"some string padding some string padding some string padd {
                #: {somedict['dictkey2']}")
                somedict['key1']}, more padding more paddin

```
Notice the second-to-last line should actually be the last line. The resulting formatted code is not syntactically correct.

## Your Environment
* Python version: Python 3.12.3
* autopep8 version: autopep8 2.3.0 (pycodestyle: 2.12.0)
* Platform: Linux (Fedora 40)

**Comment by hhatto** [comment]
Thanks for reporting 👍 

fix and v2.3.1 has been released.
https://pypi.org/project/autopep8/2.3.1/
