### ISSUE TITLE
extra line added for docstring with class

### ISSUE THREAD

**Issue by gsemet** [hhatto/autopep8#83]
I've found the following issue with autopep8 when E0301 is enabled:

class SomeClass(object)
   '''the docstring of the class'''

becomes
class SomeClass(object)

   '''the docstring of the class'''

while I think this should not. This doesn't happen for function/method docstring.

I'm using autopep8 v0.9.3

Regards

**Comment by r-owen** [comment]
Is there a way to disable this behavior? It does not match our own standards and I'd like to turn it off.
