### ISSUE TITLE
--exclude to filter directories as well as files?

### ISSUE THREAD

**Issue by andrew-wroe** [hhatto/autopep8#92]
I'm using _autopep8_ in conjunction with _flake8_. For the later --exclude allows me to filter out directories as well as files, so I can point it at my top level folder and then get it to skip certain paths.

I'd like to see the same behaviour in _autopep8_ but I'm not sure if it might adversely impact the current behaviour. Does anybody have an opinion?

If there's no problem here I believe the following change will give the required behaviour:

``` python
def find_files(filenames, recursive, exclude):
    """Yield filenames."""
    while filenames:
        name = filenames.pop(0)
        if recursive and os.path.isdir(name):
            for root, directories, children in os.walk(name):
                filenames += [p for p in [os.path.join(root, f) for f in children]
                              if match_file(p, exclude)]
                directories[:] = [d for d in directories
                                  if not d.startswith('.')]
        else:
            yield name
```

Perhaps somebody can review this and submit (first time using this site and still a Python newbie).

**Comment by Tyrben** [comment]
Hello, Was this fixed? Is it now possible to filter on directories? What is the syntax?
